// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/client/v1/client.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientType describes OIDC Client type enumeration.
// https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-04#section-2.1
type ClientType int32

const (
	// Default value
	ClientType_CLIENT_TYPE_UNSPECIFIED ClientType = 0
	// Clients that have credentials and have a prior relationship with the AS are
	// designated as "confidential clients". A client that has been registered at
	// the authorization server by a registered application developer, where the
	// client is expected to be run as server-side code, would be considered a
	// confidential client.
	ClientType_CLIENT_TYPE_CONFIDENTIAL ClientType = 1
	// Clients that have credentials but no prior relationship with the AS are
	// designated as "credentialed clients". A client that runs on an end-user's
	// device, and uses Dynamic Client Registration ([RFC7591]) to establish
	// credentials the first time the app runs, would be considered a credentialed
	// client.
	ClientType_CLIENT_TYPE_CREDENTIALED ClientType = 2
	// Clients without credentials are called "public clients". An application
	// deployed as a single-page app on a static web host would be considered a
	// public client.
	ClientType_CLIENT_TYPE_PUBLIC ClientType = 3
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLIENT_TYPE_UNSPECIFIED",
		1: "CLIENT_TYPE_CONFIDENTIAL",
		2: "CLIENT_TYPE_CREDENTIALED",
		3: "CLIENT_TYPE_PUBLIC",
	}
	ClientType_value = map[string]int32{
		"CLIENT_TYPE_UNSPECIFIED":  0,
		"CLIENT_TYPE_CONFIDENTIAL": 1,
		"CLIENT_TYPE_CREDENTIALED": 2,
		"CLIENT_TYPE_PUBLIC":       3,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_oidc_client_v1_client_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_oidc_client_v1_client_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{0}
}

// ClientProfile describes client profile enumeration.
// https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-04#section-2.1
type ClientProfile int32

const (
	// Default value
	ClientProfile_CLIENT_PROFILE_UNSPECIFIED ClientProfile = 0
	// A web application is a confidential client
	// running on a web server.  Resource owners access the client via an
	// HTML user interface rendered in a user agent on the device used by
	// the resource owner.  The client credentials as well as any access
	// tokens issued to the client are stored on the web server and are
	// not exposed to or accessible by the resource owner.
	ClientProfile_CLIENT_PROFILE_WEB_APPLICATION ClientProfile = 1
	// A browser-based application is a public
	// client in which the client code is downloaded from a web server
	// and executes within a user agent (e.g., web browser) on the device
	// used by the resource owner.  Protocol data and credentials are
	// easily accessible (and often visible) to the resource owner.
	// Since such applications reside within the user agent, they can
	// make seamless use of the user agent capabilities when requesting
	// authorization.
	ClientProfile_CLIENT_PROFILE_BROWSER_BASED_APPLICATION ClientProfile = 2
	// A native application is a public client
	// installed and executed on the device used by the resource owner.
	// Protocol data and credentials are accessible to the resource
	// owner.  It is assumed that any client authentication credentials
	// included in the application can be extracted.  On the other hand,
	// dynamically issued credentials such as access tokens or refresh
	// tokens can receive an acceptable level of protection.  At a
	// minimum, these credentials are protected from hostile servers with
	// which the application may interact.  On some platforms, these
	// credentials might be protected from other applications residing on
	// the same device.
	ClientProfile_CLIENT_PROFILE_NATIVE_APPLICATION ClientProfile = 3
)

// Enum value maps for ClientProfile.
var (
	ClientProfile_name = map[int32]string{
		0: "CLIENT_PROFILE_UNSPECIFIED",
		1: "CLIENT_PROFILE_WEB_APPLICATION",
		2: "CLIENT_PROFILE_BROWSER_BASED_APPLICATION",
		3: "CLIENT_PROFILE_NATIVE_APPLICATION",
	}
	ClientProfile_value = map[string]int32{
		"CLIENT_PROFILE_UNSPECIFIED":               0,
		"CLIENT_PROFILE_WEB_APPLICATION":           1,
		"CLIENT_PROFILE_BROWSER_BASED_APPLICATION": 2,
		"CLIENT_PROFILE_NATIVE_APPLICATION":        3,
	}
)

func (x ClientProfile) Enum() *ClientProfile {
	p := new(ClientProfile)
	*p = x
	return p
}

func (x ClientProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_oidc_client_v1_client_proto_enumTypes[1].Descriptor()
}

func (ClientProfile) Type() protoreflect.EnumType {
	return &file_oidc_client_v1_client_proto_enumTypes[1]
}

func (x ClientProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientProfile.Descriptor instead.
func (ClientProfile) EnumDescriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{1}
}

// Client defines internal OIDC client properties.
type Client struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	ClientId                              string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientType                            ClientType             `protobuf:"varint,2,opt,name=client_type,json=clientType,proto3,enum=oidc.client.v1.ClientType" json:"client_type,omitempty"`
	RedirectUris                          []string               `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	ResponseTypes                         []string               `protobuf:"bytes,4,rep,name=response_types,json=responseTypes,proto3" json:"response_types,omitempty"`
	ResponseModes                         []string               `protobuf:"bytes,5,rep,name=response_modes,json=responseModes,proto3" json:"response_modes,omitempty"`
	GrantTypes                            []string               `protobuf:"bytes,6,rep,name=grant_types,json=grantTypes,proto3" json:"grant_types,omitempty"`
	ApplicationType                       string                 `protobuf:"bytes,7,opt,name=application_type,json=applicationType,proto3" json:"application_type,omitempty"`
	Contacts                              []string               `protobuf:"bytes,8,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ClientName                            string                 `protobuf:"bytes,9,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	LogoUri                               string                 `protobuf:"bytes,10,opt,name=logo_uri,json=logoUri,proto3" json:"logo_uri,omitempty"`
	ClientUri                             string                 `protobuf:"bytes,11,opt,name=client_uri,json=clientUri,proto3" json:"client_uri,omitempty"`
	PolicyUri                             string                 `protobuf:"bytes,12,opt,name=policy_uri,json=policyUri,proto3" json:"policy_uri,omitempty"`
	TosUri                                string                 `protobuf:"bytes,13,opt,name=tos_uri,json=tosUri,proto3" json:"tos_uri,omitempty"`
	JwksUri                               string                 `protobuf:"bytes,14,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	Jwks                                  []byte                 `protobuf:"bytes,15,opt,name=jwks,proto3" json:"jwks,omitempty"`
	ClientSecret                          []byte                 `protobuf:"bytes,16,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	SubjectType                           string                 `protobuf:"bytes,17,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SectorIdentifier                      string                 `protobuf:"bytes,18,opt,name=sector_identifier,json=sectorIdentifier,proto3" json:"sector_identifier,omitempty"`
	TokenEndpointAuthMethod               string                 `protobuf:"bytes,19,opt,name=token_endpoint_auth_method,json=tokenEndpointAuthMethod,proto3" json:"token_endpoint_auth_method,omitempty"`
	TlsClientAuthSubjectDn                string                 `protobuf:"bytes,20,opt,name=tls_client_auth_subject_dn,json=tlsClientAuthSubjectDn,proto3" json:"tls_client_auth_subject_dn,omitempty"`
	TlsClientAuthSanDns                   string                 `protobuf:"bytes,21,opt,name=tls_client_auth_san_dns,json=tlsClientAuthSanDns,proto3" json:"tls_client_auth_san_dns,omitempty"`
	TlsClientAuthSanUri                   string                 `protobuf:"bytes,22,opt,name=tls_client_auth_san_uri,json=tlsClientAuthSanUri,proto3" json:"tls_client_auth_san_uri,omitempty"`
	TlsClientAuthSanIp                    string                 `protobuf:"bytes,23,opt,name=tls_client_auth_san_ip,json=tlsClientAuthSanIp,proto3" json:"tls_client_auth_san_ip,omitempty"`
	TlsClientAuthSanEmail                 string                 `protobuf:"bytes,24,opt,name=tls_client_auth_san_email,json=tlsClientAuthSanEmail,proto3" json:"tls_client_auth_san_email,omitempty"`
	TlsClientCertificateBoundAccessTokens bool                   `protobuf:"varint,25,opt,name=tls_client_certificate_bound_access_tokens,json=tlsClientCertificateBoundAccessTokens,proto3" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	RequirePushedAuthorizationRequests    bool                   `protobuf:"varint,26,opt,name=require_pushed_authorization_requests,json=requirePushedAuthorizationRequests,proto3" json:"require_pushed_authorization_requests,omitempty"`
	RequireSignedRequestObject            bool                   `protobuf:"varint,27,opt,name=require_signed_request_object,json=requireSignedRequestObject,proto3" json:"require_signed_request_object,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc9449#section-5.2
	DpopBoundAccessTokens bool `protobuf:"varint,28,opt,name=dpop_bound_access_tokens,json=dpopBoundAccessTokens,proto3" json:"dpop_bound_access_tokens,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE ID of the
	// workload the client identity is bound to; MAY end with /* (wildcard
	// over complete path segments).
	SpiffeId string `protobuf:"bytes,29,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE bundle
	// endpoint serving the trust domain bundle.
	SpiffeBundleEndpoint string `protobuf:"bytes,30,opt,name=spiffe_bundle_endpoint,json=spiffeBundleEndpoint,proto3" json:"spiffe_bundle_endpoint,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: pre-configured
	// SPIFFE bundle (JWKS) for the client's trust domain, the static
	SpiffeBundle []byte `protobuf:"bytes,31,opt,name=spiffe_bundle,json=spiffeBundle,proto3" json:"spiffe_bundle,omitempty"`
	// RFC 7662 section 2.1: client identifiers authorized by this client
	// to introspect its tokens at the introspection endpoint (resource
	// servers acting as delegates). The token owner itself is always
	// allowed; anyone else receives the no-cause-distinction inactive
	// envelope.
	AuthorizedIntrospectionClients []string `protobuf:"bytes,32,rep,name=authorized_introspection_clients,json=authorizedIntrospectionClients,proto3" json:"authorized_introspection_clients,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_oidc_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Client) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

func (x *Client) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *Client) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *Client) GetResponseModes() []string {
	if x != nil {
		return x.ResponseModes
	}
	return nil
}

func (x *Client) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *Client) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *Client) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *Client) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Client) GetLogoUri() string {
	if x != nil {
		return x.LogoUri
	}
	return ""
}

func (x *Client) GetClientUri() string {
	if x != nil {
		return x.ClientUri
	}
	return ""
}

func (x *Client) GetPolicyUri() string {
	if x != nil {
		return x.PolicyUri
	}
	return ""
}

func (x *Client) GetTosUri() string {
	if x != nil {
		return x.TosUri
	}
	return ""
}

func (x *Client) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *Client) GetJwks() []byte {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *Client) GetClientSecret() []byte {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

func (x *Client) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Client) GetSectorIdentifier() string {
	if x != nil {
		return x.SectorIdentifier
	}
	return ""
}

func (x *Client) GetTokenEndpointAuthMethod() string {
	if x != nil {
		return x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *Client) GetTlsClientAuthSubjectDn() string {
	if x != nil {
		return x.TlsClientAuthSubjectDn
	}
	return ""
}

func (x *Client) GetTlsClientAuthSanDns() string {
	if x != nil {
		return x.TlsClientAuthSanDns
	}
	return ""
}

func (x *Client) GetTlsClientAuthSanUri() string {
	if x != nil {
		return x.TlsClientAuthSanUri
	}
	return ""
}

func (x *Client) GetTlsClientAuthSanIp() string {
	if x != nil {
		return x.TlsClientAuthSanIp
	}
	return ""
}

func (x *Client) GetTlsClientAuthSanEmail() string {
	if x != nil {
		return x.TlsClientAuthSanEmail
	}
	return ""
}

func (x *Client) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil {
		return x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

func (x *Client) GetRequirePushedAuthorizationRequests() bool {
	if x != nil {
		return x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *Client) GetRequireSignedRequestObject() bool {
	if x != nil {
		return x.RequireSignedRequestObject
	}
	return false
}

func (x *Client) GetDpopBoundAccessTokens() bool {
	if x != nil {
		return x.DpopBoundAccessTokens
	}
	return false
}

func (x *Client) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *Client) GetSpiffeBundleEndpoint() string {
	if x != nil {
		return x.SpiffeBundleEndpoint
	}
	return ""
}

func (x *Client) GetSpiffeBundle() []byte {
	if x != nil {
		return x.SpiffeBundle
	}
	return nil
}

func (x *Client) GetAuthorizedIntrospectionClients() []string {
	if x != nil {
		return x.AuthorizedIntrospectionClients
	}
	return nil
}

type ClientMeta struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	ApplicationType                       *string                `protobuf:"bytes,1,opt,name=application_type,json=applicationType,proto3,oneof" json:"application_type,omitempty"`
	RedirectUris                          []string               `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TokenEndpointAuthMethod               *string                `protobuf:"bytes,3,opt,name=token_endpoint_auth_method,json=tokenEndpointAuthMethod,proto3,oneof" json:"token_endpoint_auth_method,omitempty"`
	GrantTypes                            []string               `protobuf:"bytes,4,rep,name=grant_types,json=grantTypes,proto3" json:"grant_types,omitempty"`
	ResponseTypes                         []string               `protobuf:"bytes,5,rep,name=response_types,json=responseTypes,proto3" json:"response_types,omitempty"`
	ClientName                            *string                `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3,oneof" json:"client_name,omitempty"`
	ClientNameI18N                        map[string]string      `protobuf:"bytes,7,rep,name=client_name_i18n,json=clientNameI18n,proto3" json:"client_name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientUri                             *string                `protobuf:"bytes,8,opt,name=client_uri,json=clientUri,proto3,oneof" json:"client_uri,omitempty"`
	LogoUri                               *string                `protobuf:"bytes,9,opt,name=logo_uri,json=logoUri,proto3,oneof" json:"logo_uri,omitempty"`
	LogoUriI18N                           map[string]string      `protobuf:"bytes,10,rep,name=logo_uri_i18n,json=logoUriI18n,proto3" json:"logo_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Scope                                 *string                `protobuf:"bytes,11,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	Contacts                              []string               `protobuf:"bytes,12,rep,name=contacts,proto3" json:"contacts,omitempty"`
	TosUri                                *string                `protobuf:"bytes,13,opt,name=tos_uri,json=tosUri,proto3,oneof" json:"tos_uri,omitempty"`
	TosUriI18N                            map[string]string      `protobuf:"bytes,14,rep,name=tos_uri_i18n,json=tosUriI18n,proto3" json:"tos_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PolicyUri                             *string                `protobuf:"bytes,15,opt,name=policy_uri,json=policyUri,proto3,oneof" json:"policy_uri,omitempty"`
	PolicyUriI18N                         map[string]string      `protobuf:"bytes,16,rep,name=policy_uri_i18n,json=policyUriI18n,proto3" json:"policy_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JwkUri                                *string                `protobuf:"bytes,17,opt,name=jwk_uri,json=jwkUri,proto3,oneof" json:"jwk_uri,omitempty"`
	Jwks                                  []byte                 `protobuf:"bytes,18,opt,name=jwks,proto3,oneof" json:"jwks,omitempty"`
	SoftwareId                            *string                `protobuf:"bytes,19,opt,name=software_id,json=softwareId,proto3,oneof" json:"software_id,omitempty"`
	SoftwareVersion                       *string                `protobuf:"bytes,20,opt,name=software_version,json=softwareVersion,proto3,oneof" json:"software_version,omitempty"`
	SoftwareStatement                     *string                `protobuf:"bytes,21,opt,name=software_statement,json=softwareStatement,proto3,oneof" json:"software_statement,omitempty"`
	SubjectType                           *string                `protobuf:"bytes,22,opt,name=subject_type,json=subjectType,proto3,oneof" json:"subject_type,omitempty"`
	SectorIdentifier                      *string                `protobuf:"bytes,23,opt,name=sector_identifier,json=sectorIdentifier,proto3,oneof" json:"sector_identifier,omitempty"`
	TlsClientAuthSubjectDn                *string                `protobuf:"bytes,24,opt,name=tls_client_auth_subject_dn,json=tlsClientAuthSubjectDn,proto3,oneof" json:"tls_client_auth_subject_dn,omitempty"`
	TlsClientAuthSanDns                   *string                `protobuf:"bytes,25,opt,name=tls_client_auth_san_dns,json=tlsClientAuthSanDns,proto3,oneof" json:"tls_client_auth_san_dns,omitempty"`
	TlsClientAuthSanUri                   *string                `protobuf:"bytes,26,opt,name=tls_client_auth_san_uri,json=tlsClientAuthSanUri,proto3,oneof" json:"tls_client_auth_san_uri,omitempty"`
	TlsClientAuthSanIp                    *string                `protobuf:"bytes,27,opt,name=tls_client_auth_san_ip,json=tlsClientAuthSanIp,proto3,oneof" json:"tls_client_auth_san_ip,omitempty"`
	TlsClientAuthSanEmail                 *string                `protobuf:"bytes,28,opt,name=tls_client_auth_san_email,json=tlsClientAuthSanEmail,proto3,oneof" json:"tls_client_auth_san_email,omitempty"`
	TlsClientCertificateBoundAccessTokens *bool                  `protobuf:"varint,29,opt,name=tls_client_certificate_bound_access_tokens,json=tlsClientCertificateBoundAccessTokens,proto3,oneof" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	IntrospectionSignedResponseAlg        *string                `protobuf:"bytes,30,opt,name=introspection_signed_response_alg,json=introspectionSignedResponseAlg,proto3,oneof" json:"introspection_signed_response_alg,omitempty"`
	IntrospectionEncryptedResponseAlg     *string                `protobuf:"bytes,31,opt,name=introspection_encrypted_response_alg,json=introspectionEncryptedResponseAlg,proto3,oneof" json:"introspection_encrypted_response_alg,omitempty"`
	IntrospectionEncryptedResponseEnc     *string                `protobuf:"bytes,32,opt,name=introspection_encrypted_response_enc,json=introspectionEncryptedResponseEnc,proto3,oneof" json:"introspection_encrypted_response_enc,omitempty"`
	ResponseModes                         []string               `protobuf:"bytes,33,rep,name=response_modes,json=responseModes,proto3" json:"response_modes,omitempty"`
	RequirePushedAuthorizationRequests    *bool                  `protobuf:"varint,34,opt,name=require_pushed_authorization_requests,json=requirePushedAuthorizationRequests,proto3,oneof" json:"require_pushed_authorization_requests,omitempty"`
	RequireSignedRequestObject            *bool                  `protobuf:"varint,35,opt,name=require_signed_request_object,json=requireSignedRequestObject,proto3,oneof" json:"require_signed_request_object,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc9449#section-5.2
	DpopBoundAccessTokens *bool `protobuf:"varint,36,opt,name=dpop_bound_access_tokens,json=dpopBoundAccessTokens,proto3,oneof" json:"dpop_bound_access_tokens,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE ID of the
	// workload the client identity is bound to; MAY end with /* (wildcard
	// over complete path segments).
	SpiffeId *string `protobuf:"bytes,37,opt,name=spiffe_id,json=spiffeId,proto3,oneof" json:"spiffe_id,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE bundle
	// endpoint serving the trust domain bundle.
	SpiffeBundleEndpoint *string `protobuf:"bytes,38,opt,name=spiffe_bundle_endpoint,json=spiffeBundleEndpoint,proto3,oneof" json:"spiffe_bundle_endpoint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientMeta) Reset() {
	*x = ClientMeta{}
	mi := &file_oidc_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMeta) ProtoMessage() {}

func (x *ClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMeta.ProtoReflect.Descriptor instead.
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMeta) GetApplicationType() string {
	if x != nil && x.ApplicationType != nil {
		return *x.ApplicationType
	}
	return ""
}

func (x *ClientMeta) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *ClientMeta) GetTokenEndpointAuthMethod() string {
	if x != nil && x.TokenEndpointAuthMethod != nil {
		return *x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *ClientMeta) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *ClientMeta) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *ClientMeta) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *ClientMeta) GetClientNameI18N() map[string]string {
	if x != nil {
		return x.ClientNameI18N
	}
	return nil
}

func (x *ClientMeta) GetClientUri() string {
	if x != nil && x.ClientUri != nil {
		return *x.ClientUri
	}
	return ""
}

func (x *ClientMeta) GetLogoUri() string {
	if x != nil && x.LogoUri != nil {
		return *x.LogoUri
	}
	return ""
}

func (x *ClientMeta) GetLogoUriI18N() map[string]string {
	if x != nil {
		return x.LogoUriI18N
	}
	return nil
}

func (x *ClientMeta) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *ClientMeta) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ClientMeta) GetTosUri() string {
	if x != nil && x.TosUri != nil {
		return *x.TosUri
	}
	return ""
}

func (x *ClientMeta) GetTosUriI18N() map[string]string {
	if x != nil {
		return x.TosUriI18N
	}
	return nil
}

func (x *ClientMeta) GetPolicyUri() string {
	if x != nil && x.PolicyUri != nil {
		return *x.PolicyUri
	}
	return ""
}

func (x *ClientMeta) GetPolicyUriI18N() map[string]string {
	if x != nil {
		return x.PolicyUriI18N
	}
	return nil
}

func (x *ClientMeta) GetJwkUri() string {
	if x != nil && x.JwkUri != nil {
		return *x.JwkUri
	}
	return ""
}

func (x *ClientMeta) GetJwks() []byte {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *ClientMeta) GetSoftwareId() string {
	if x != nil && x.SoftwareId != nil {
		return *x.SoftwareId
	}
	return ""
}

func (x *ClientMeta) GetSoftwareVersion() string {
	if x != nil && x.SoftwareVersion != nil {
		return *x.SoftwareVersion
	}
	return ""
}

func (x *ClientMeta) GetSoftwareStatement() string {
	if x != nil && x.SoftwareStatement != nil {
		return *x.SoftwareStatement
	}
	return ""
}

func (x *ClientMeta) GetSubjectType() string {
	if x != nil && x.SubjectType != nil {
		return *x.SubjectType
	}
	return ""
}

func (x *ClientMeta) GetSectorIdentifier() string {
	if x != nil && x.SectorIdentifier != nil {
		return *x.SectorIdentifier
	}
	return ""
}

func (x *ClientMeta) GetTlsClientAuthSubjectDn() string {
	if x != nil && x.TlsClientAuthSubjectDn != nil {
		return *x.TlsClientAuthSubjectDn
	}
	return ""
}

func (x *ClientMeta) GetTlsClientAuthSanDns() string {
	if x != nil && x.TlsClientAuthSanDns != nil {
		return *x.TlsClientAuthSanDns
	}
	return ""
}

func (x *ClientMeta) GetTlsClientAuthSanUri() string {
	if x != nil && x.TlsClientAuthSanUri != nil {
		return *x.TlsClientAuthSanUri
	}
	return ""
}

func (x *ClientMeta) GetTlsClientAuthSanIp() string {
	if x != nil && x.TlsClientAuthSanIp != nil {
		return *x.TlsClientAuthSanIp
	}
	return ""
}

func (x *ClientMeta) GetTlsClientAuthSanEmail() string {
	if x != nil && x.TlsClientAuthSanEmail != nil {
		return *x.TlsClientAuthSanEmail
	}
	return ""
}

func (x *ClientMeta) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil && x.TlsClientCertificateBoundAccessTokens != nil {
		return *x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

func (x *ClientMeta) GetIntrospectionSignedResponseAlg() string {
	if x != nil && x.IntrospectionSignedResponseAlg != nil {
		return *x.IntrospectionSignedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetIntrospectionEncryptedResponseAlg() string {
	if x != nil && x.IntrospectionEncryptedResponseAlg != nil {
		return *x.IntrospectionEncryptedResponseAlg
	}
	return ""
}

func (x *ClientMeta) GetIntrospectionEncryptedResponseEnc() string {
	if x != nil && x.IntrospectionEncryptedResponseEnc != nil {
		return *x.IntrospectionEncryptedResponseEnc
	}
	return ""
}

func (x *ClientMeta) GetResponseModes() []string {
	if x != nil {
		return x.ResponseModes
	}
	return nil
}

func (x *ClientMeta) GetRequirePushedAuthorizationRequests() bool {
	if x != nil && x.RequirePushedAuthorizationRequests != nil {
		return *x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *ClientMeta) GetRequireSignedRequestObject() bool {
	if x != nil && x.RequireSignedRequestObject != nil {
		return *x.RequireSignedRequestObject
	}
	return false
}

func (x *ClientMeta) GetDpopBoundAccessTokens() bool {
	if x != nil && x.DpopBoundAccessTokens != nil {
		return *x.DpopBoundAccessTokens
	}
	return false
}

func (x *ClientMeta) GetSpiffeId() string {
	if x != nil && x.SpiffeId != nil {
		return *x.SpiffeId
	}
	return ""
}

func (x *ClientMeta) GetSpiffeBundleEndpoint() string {
	if x != nil && x.SpiffeBundleEndpoint != nil {
		return *x.SpiffeBundleEndpoint
	}
	return ""
}

// ClientIDMetadataDocument mirrors the Client ID Metadata Document wire format
// defined by the OAuth Client ID Metadata Document draft. Properties use the
// RFC 7591 client-metadata JSON names. client_secret and
// client_secret_expires_at are carried so the resolver can REJECT documents
// containing them (draft-ietf-oauth-client-id-metadata-document, section 4.1).
type ClientIDMetadataDocument struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	ClientId                           *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	RedirectUris                       []string               `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TokenEndpointAuthMethod            *string                `protobuf:"bytes,3,opt,name=token_endpoint_auth_method,json=tokenEndpointAuthMethod,proto3,oneof" json:"token_endpoint_auth_method,omitempty"`
	GrantTypes                         []string               `protobuf:"bytes,4,rep,name=grant_types,json=grantTypes,proto3" json:"grant_types,omitempty"`
	ResponseTypes                      []string               `protobuf:"bytes,5,rep,name=response_types,json=responseTypes,proto3" json:"response_types,omitempty"`
	ClientName                         *string                `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3,oneof" json:"client_name,omitempty"`
	ClientNameI18N                     map[string]string      `protobuf:"bytes,7,rep,name=client_name_i18n,json=clientNameI18n,proto3" json:"client_name_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientUri                          *string                `protobuf:"bytes,8,opt,name=client_uri,json=clientUri,proto3,oneof" json:"client_uri,omitempty"`
	LogoUri                            *string                `protobuf:"bytes,9,opt,name=logo_uri,json=logoUri,proto3,oneof" json:"logo_uri,omitempty"`
	LogoUriI18N                        map[string]string      `protobuf:"bytes,10,rep,name=logo_uri_i18n,json=logoUriI18n,proto3" json:"logo_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Scope                              *string                `protobuf:"bytes,11,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	Contacts                           []string               `protobuf:"bytes,12,rep,name=contacts,proto3" json:"contacts,omitempty"`
	TosUri                             *string                `protobuf:"bytes,13,opt,name=tos_uri,json=tosUri,proto3,oneof" json:"tos_uri,omitempty"`
	TosUriI18N                         map[string]string      `protobuf:"bytes,14,rep,name=tos_uri_i18n,json=tosUriI18n,proto3" json:"tos_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PolicyUri                          *string                `protobuf:"bytes,15,opt,name=policy_uri,json=policyUri,proto3,oneof" json:"policy_uri,omitempty"`
	PolicyUriI18N                      map[string]string      `protobuf:"bytes,16,rep,name=policy_uri_i18n,json=policyUriI18n,proto3" json:"policy_uri_i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JwksUri                            *string                `protobuf:"bytes,17,opt,name=jwks_uri,json=jwksUri,proto3,oneof" json:"jwks_uri,omitempty"`
	Jwks                               []byte                 `protobuf:"bytes,18,opt,name=jwks,proto3,oneof" json:"jwks,omitempty"`
	SoftwareId                         *string                `protobuf:"bytes,19,opt,name=software_id,json=softwareId,proto3,oneof" json:"software_id,omitempty"`
	SoftwareVersion                    *string                `protobuf:"bytes,20,opt,name=software_version,json=softwareVersion,proto3,oneof" json:"software_version,omitempty"`
	SoftwareStatement                  *string                `protobuf:"bytes,21,opt,name=software_statement,json=softwareStatement,proto3,oneof" json:"software_statement,omitempty"`
	SubjectType                        *string                `protobuf:"bytes,22,opt,name=subject_type,json=subjectType,proto3,oneof" json:"subject_type,omitempty"`
	SectorIdentifier                   *string                `protobuf:"bytes,23,opt,name=sector_identifier,json=sectorIdentifier,proto3,oneof" json:"sector_identifier,omitempty"`
	ResponseModes                      []string               `protobuf:"bytes,24,rep,name=response_modes,json=responseModes,proto3" json:"response_modes,omitempty"`
	RequirePushedAuthorizationRequests *bool                  `protobuf:"varint,25,opt,name=require_pushed_authorization_requests,json=requirePushedAuthorizationRequests,proto3,oneof" json:"require_pushed_authorization_requests,omitempty"`
	RequireSignedRequestObject         *bool                  `protobuf:"varint,26,opt,name=require_signed_request_object,json=requireSignedRequestObject,proto3,oneof" json:"require_signed_request_object,omitempty"`
	// https://datatracker.ietf.org/doc/html/rfc9449#section-5.2
	DpopBoundAccessTokens *bool `protobuf:"varint,27,opt,name=dpop_bound_access_tokens,json=dpopBoundAccessTokens,proto3,oneof" json:"dpop_bound_access_tokens,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE ID of the
	// workload the client identity is bound to; MAY end with /* (wildcard
	// over complete path segments).
	SpiffeId *string `protobuf:"bytes,30,opt,name=spiffe_id,json=spiffeId,proto3,oneof" json:"spiffe_id,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 5.1: SPIFFE bundle
	// endpoint serving the trust domain bundle.
	SpiffeBundleEndpoint *string `protobuf:"bytes,31,opt,name=spiffe_bundle_endpoint,json=spiffeBundleEndpoint,proto3,oneof" json:"spiffe_bundle_endpoint,omitempty"`
	// Present in the wire format so the resolver can REJECT documents containing
	// them (section 4.1: they MUST NOT be used).
	ClientSecret          *string `protobuf:"bytes,28,opt,name=client_secret,json=clientSecret,proto3,oneof" json:"client_secret,omitempty"`
	ClientSecretExpiresAt *int64  `protobuf:"varint,29,opt,name=client_secret_expires_at,json=clientSecretExpiresAt,proto3,oneof" json:"client_secret_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientIDMetadataDocument) Reset() {
	*x = ClientIDMetadataDocument{}
	mi := &file_oidc_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientIDMetadataDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIDMetadataDocument) ProtoMessage() {}

func (x *ClientIDMetadataDocument) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIDMetadataDocument.ProtoReflect.Descriptor instead.
func (*ClientIDMetadataDocument) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientIDMetadataDocument) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetTokenEndpointAuthMethod() string {
	if x != nil && x.TokenEndpointAuthMethod != nil {
		return *x.TokenEndpointAuthMethod
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetGrantTypes() []string {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetResponseTypes() []string {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetClientNameI18N() map[string]string {
	if x != nil {
		return x.ClientNameI18N
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetClientUri() string {
	if x != nil && x.ClientUri != nil {
		return *x.ClientUri
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetLogoUri() string {
	if x != nil && x.LogoUri != nil {
		return *x.LogoUri
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetLogoUriI18N() map[string]string {
	if x != nil {
		return x.LogoUriI18N
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetTosUri() string {
	if x != nil && x.TosUri != nil {
		return *x.TosUri
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetTosUriI18N() map[string]string {
	if x != nil {
		return x.TosUriI18N
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetPolicyUri() string {
	if x != nil && x.PolicyUri != nil {
		return *x.PolicyUri
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetPolicyUriI18N() map[string]string {
	if x != nil {
		return x.PolicyUriI18N
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetJwksUri() string {
	if x != nil && x.JwksUri != nil {
		return *x.JwksUri
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetJwks() []byte {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetSoftwareId() string {
	if x != nil && x.SoftwareId != nil {
		return *x.SoftwareId
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetSoftwareVersion() string {
	if x != nil && x.SoftwareVersion != nil {
		return *x.SoftwareVersion
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetSoftwareStatement() string {
	if x != nil && x.SoftwareStatement != nil {
		return *x.SoftwareStatement
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetSubjectType() string {
	if x != nil && x.SubjectType != nil {
		return *x.SubjectType
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetSectorIdentifier() string {
	if x != nil && x.SectorIdentifier != nil {
		return *x.SectorIdentifier
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetResponseModes() []string {
	if x != nil {
		return x.ResponseModes
	}
	return nil
}

func (x *ClientIDMetadataDocument) GetRequirePushedAuthorizationRequests() bool {
	if x != nil && x.RequirePushedAuthorizationRequests != nil {
		return *x.RequirePushedAuthorizationRequests
	}
	return false
}

func (x *ClientIDMetadataDocument) GetRequireSignedRequestObject() bool {
	if x != nil && x.RequireSignedRequestObject != nil {
		return *x.RequireSignedRequestObject
	}
	return false
}

func (x *ClientIDMetadataDocument) GetDpopBoundAccessTokens() bool {
	if x != nil && x.DpopBoundAccessTokens != nil {
		return *x.DpopBoundAccessTokens
	}
	return false
}

func (x *ClientIDMetadataDocument) GetSpiffeId() string {
	if x != nil && x.SpiffeId != nil {
		return *x.SpiffeId
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetSpiffeBundleEndpoint() string {
	if x != nil && x.SpiffeBundleEndpoint != nil {
		return *x.SpiffeBundleEndpoint
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	return ""
}

func (x *ClientIDMetadataDocument) GetClientSecretExpiresAt() int64 {
	if x != nil && x.ClientSecretExpiresAt != nil {
		return *x.ClientSecretExpiresAt
	}
	return 0
}

type SoftwareStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftwareId    string                 `protobuf:"bytes,1,opt,name=software_id,json=softwareId,proto3" json:"software_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareStatement) Reset() {
	*x = SoftwareStatement{}
	mi := &file_oidc_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareStatement) ProtoMessage() {}

func (x *SoftwareStatement) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareStatement.ProtoReflect.Descriptor instead.
func (*SoftwareStatement) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *SoftwareStatement) GetSoftwareId() string {
	if x != nil {
		return x.SoftwareId
	}
	return ""
}

var File_oidc_client_v1_client_proto protoreflect.FileDescriptor

const file_oidc_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x1boidc/client/v1/client.proto\x12\x0eoidc.client.v1\"\xb3\v\n" +
	"\x06Client\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12;\n" +
	"\vclient_type\x18\x02 \x01(\x0e2\x1a.oidc.client.v1.ClientTypeR\n" +
	"clientType\x12#\n" +
	"\rredirect_uris\x18\x03 \x03(\tR\fredirectUris\x12%\n" +
	"\x0eresponse_types\x18\x04 \x03(\tR\rresponseTypes\x12%\n" +
	"\x0eresponse_modes\x18\x05 \x03(\tR\rresponseModes\x12\x1f\n" +
	"\vgrant_types\x18\x06 \x03(\tR\n" +
	"grantTypes\x12)\n" +
	"\x10application_type\x18\a \x01(\tR\x0fapplicationType\x12\x1a\n" +
	"\bcontacts\x18\b \x03(\tR\bcontacts\x12\x1f\n" +
	"\vclient_name\x18\t \x01(\tR\n" +
	"clientName\x12\x19\n" +
	"\blogo_uri\x18\n" +
	" \x01(\tR\alogoUri\x12\x1d\n" +
	"\n" +
	"client_uri\x18\v \x01(\tR\tclientUri\x12\x1d\n" +
	"\n" +
	"policy_uri\x18\f \x01(\tR\tpolicyUri\x12\x17\n" +
	"\atos_uri\x18\r \x01(\tR\x06tosUri\x12\x19\n" +
	"\bjwks_uri\x18\x0e \x01(\tR\ajwksUri\x12\x12\n" +
	"\x04jwks\x18\x0f \x01(\fR\x04jwks\x12#\n" +
	"\rclient_secret\x18\x10 \x01(\fR\fclientSecret\x12!\n" +
	"\fsubject_type\x18\x11 \x01(\tR\vsubjectType\x12+\n" +
	"\x11sector_identifier\x18\x12 \x01(\tR\x10sectorIdentifier\x12;\n" +
	"\x1atoken_endpoint_auth_method\x18\x13 \x01(\tR\x17tokenEndpointAuthMethod\x12:\n" +
	"\x1atls_client_auth_subject_dn\x18\x14 \x01(\tR\x16tlsClientAuthSubjectDn\x124\n" +
	"\x17tls_client_auth_san_dns\x18\x15 \x01(\tR\x13tlsClientAuthSanDns\x124\n" +
	"\x17tls_client_auth_san_uri\x18\x16 \x01(\tR\x13tlsClientAuthSanUri\x122\n" +
	"\x16tls_client_auth_san_ip\x18\x17 \x01(\tR\x12tlsClientAuthSanIp\x128\n" +
	"\x19tls_client_auth_san_email\x18\x18 \x01(\tR\x15tlsClientAuthSanEmail\x12Y\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x19 \x01(\bR%tlsClientCertificateBoundAccessTokens\x12Q\n" +
	"%require_pushed_authorization_requests\x18\x1a \x01(\bR\"requirePushedAuthorizationRequests\x12A\n" +
	"\x1drequire_signed_request_object\x18\x1b \x01(\bR\x1arequireSignedRequestObject\x127\n" +
	"\x18dpop_bound_access_tokens\x18\x1c \x01(\bR\x15dpopBoundAccessTokens\x12\x1b\n" +
	"\tspiffe_id\x18\x1d \x01(\tR\bspiffeId\x124\n" +
	"\x16spiffe_bundle_endpoint\x18\x1e \x01(\tR\x14spiffeBundleEndpoint\x12#\n" +
	"\rspiffe_bundle\x18\x1f \x01(\fR\fspiffeBundle\x12H\n" +
	" authorized_introspection_clients\x18  \x03(\tR\x1eauthorizedIntrospectionClients\"\xf0\x17\n" +
	"\n" +
	"ClientMeta\x12.\n" +
	"\x10application_type\x18\x01 \x01(\tH\x00R\x0fapplicationType\x88\x01\x01\x12#\n" +
	"\rredirect_uris\x18\x02 \x03(\tR\fredirectUris\x12@\n" +
	"\x1atoken_endpoint_auth_method\x18\x03 \x01(\tH\x01R\x17tokenEndpointAuthMethod\x88\x01\x01\x12\x1f\n" +
	"\vgrant_types\x18\x04 \x03(\tR\n" +
	"grantTypes\x12%\n" +
	"\x0eresponse_types\x18\x05 \x03(\tR\rresponseTypes\x12$\n" +
	"\vclient_name\x18\x06 \x01(\tH\x02R\n" +
	"clientName\x88\x01\x01\x12X\n" +
	"\x10client_name_i18n\x18\a \x03(\v2..oidc.client.v1.ClientMeta.ClientNameI18nEntryR\x0eclientNameI18n\x12\"\n" +
	"\n" +
	"client_uri\x18\b \x01(\tH\x03R\tclientUri\x88\x01\x01\x12\x1e\n" +
	"\blogo_uri\x18\t \x01(\tH\x04R\alogoUri\x88\x01\x01\x12O\n" +
	"\rlogo_uri_i18n\x18\n" +
	" \x03(\v2+.oidc.client.v1.ClientMeta.LogoUriI18nEntryR\vlogoUriI18n\x12\x19\n" +
	"\x05scope\x18\v \x01(\tH\x05R\x05scope\x88\x01\x01\x12\x1a\n" +
	"\bcontacts\x18\f \x03(\tR\bcontacts\x12\x1c\n" +
	"\atos_uri\x18\r \x01(\tH\x06R\x06tosUri\x88\x01\x01\x12L\n" +
	"\ftos_uri_i18n\x18\x0e \x03(\v2*.oidc.client.v1.ClientMeta.TosUriI18nEntryR\n" +
	"tosUriI18n\x12\"\n" +
	"\n" +
	"policy_uri\x18\x0f \x01(\tH\aR\tpolicyUri\x88\x01\x01\x12U\n" +
	"\x0fpolicy_uri_i18n\x18\x10 \x03(\v2-.oidc.client.v1.ClientMeta.PolicyUriI18nEntryR\rpolicyUriI18n\x12\x1c\n" +
	"\ajwk_uri\x18\x11 \x01(\tH\bR\x06jwkUri\x88\x01\x01\x12\x17\n" +
	"\x04jwks\x18\x12 \x01(\fH\tR\x04jwks\x88\x01\x01\x12$\n" +
	"\vsoftware_id\x18\x13 \x01(\tH\n" +
	"R\n" +
	"softwareId\x88\x01\x01\x12.\n" +
	"\x10software_version\x18\x14 \x01(\tH\vR\x0fsoftwareVersion\x88\x01\x01\x122\n" +
	"\x12software_statement\x18\x15 \x01(\tH\fR\x11softwareStatement\x88\x01\x01\x12&\n" +
	"\fsubject_type\x18\x16 \x01(\tH\rR\vsubjectType\x88\x01\x01\x120\n" +
	"\x11sector_identifier\x18\x17 \x01(\tH\x0eR\x10sectorIdentifier\x88\x01\x01\x12?\n" +
	"\x1atls_client_auth_subject_dn\x18\x18 \x01(\tH\x0fR\x16tlsClientAuthSubjectDn\x88\x01\x01\x129\n" +
	"\x17tls_client_auth_san_dns\x18\x19 \x01(\tH\x10R\x13tlsClientAuthSanDns\x88\x01\x01\x129\n" +
	"\x17tls_client_auth_san_uri\x18\x1a \x01(\tH\x11R\x13tlsClientAuthSanUri\x88\x01\x01\x127\n" +
	"\x16tls_client_auth_san_ip\x18\x1b \x01(\tH\x12R\x12tlsClientAuthSanIp\x88\x01\x01\x12=\n" +
	"\x19tls_client_auth_san_email\x18\x1c \x01(\tH\x13R\x15tlsClientAuthSanEmail\x88\x01\x01\x12^\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x1d \x01(\bH\x14R%tlsClientCertificateBoundAccessTokens\x88\x01\x01\x12N\n" +
	"!introspection_signed_response_alg\x18\x1e \x01(\tH\x15R\x1eintrospectionSignedResponseAlg\x88\x01\x01\x12T\n" +
	"$introspection_encrypted_response_alg\x18\x1f \x01(\tH\x16R!introspectionEncryptedResponseAlg\x88\x01\x01\x12T\n" +
	"$introspection_encrypted_response_enc\x18  \x01(\tH\x17R!introspectionEncryptedResponseEnc\x88\x01\x01\x12%\n" +
	"\x0eresponse_modes\x18! \x03(\tR\rresponseModes\x12V\n" +
	"%require_pushed_authorization_requests\x18\" \x01(\bH\x18R\"requirePushedAuthorizationRequests\x88\x01\x01\x12F\n" +
	"\x1drequire_signed_request_object\x18# \x01(\bH\x19R\x1arequireSignedRequestObject\x88\x01\x01\x12<\n" +
	"\x18dpop_bound_access_tokens\x18$ \x01(\bH\x1aR\x15dpopBoundAccessTokens\x88\x01\x01\x12 \n" +
	"\tspiffe_id\x18% \x01(\tH\x1bR\bspiffeId\x88\x01\x01\x129\n" +
	"\x16spiffe_bundle_endpoint\x18& \x01(\tH\x1cR\x14spiffeBundleEndpoint\x88\x01\x01\x1aA\n" +
	"\x13ClientNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10LogoUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fTosUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12PolicyUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_application_typeB\x1d\n" +
	"\x1b_token_endpoint_auth_methodB\x0e\n" +
	"\f_client_nameB\r\n" +
	"\v_client_uriB\v\n" +
	"\t_logo_uriB\b\n" +
	"\x06_scopeB\n" +
	"\n" +
	"\b_tos_uriB\r\n" +
	"\v_policy_uriB\n" +
	"\n" +
	"\b_jwk_uriB\a\n" +
	"\x05_jwksB\x0e\n" +
	"\f_software_idB\x13\n" +
	"\x11_software_versionB\x15\n" +
	"\x13_software_statementB\x0f\n" +
	"\r_subject_typeB\x14\n" +
	"\x12_sector_identifierB\x1d\n" +
	"\x1b_tls_client_auth_subject_dnB\x1a\n" +
	"\x18_tls_client_auth_san_dnsB\x1a\n" +
	"\x18_tls_client_auth_san_uriB\x19\n" +
	"\x17_tls_client_auth_san_ipB\x1c\n" +
	"\x1a_tls_client_auth_san_emailB-\n" +
	"+_tls_client_certificate_bound_access_tokensB$\n" +
	"\"_introspection_signed_response_algB'\n" +
	"%_introspection_encrypted_response_algB'\n" +
	"%_introspection_encrypted_response_encB(\n" +
	"&_require_pushed_authorization_requestsB \n" +
	"\x1e_require_signed_request_objectB\x1b\n" +
	"\x19_dpop_bound_access_tokensB\f\n" +
	"\n" +
	"_spiffe_idB\x19\n" +
	"\x17_spiffe_bundle_endpoint\"\xf9\x11\n" +
	"\x18ClientIDMetadataDocument\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12#\n" +
	"\rredirect_uris\x18\x02 \x03(\tR\fredirectUris\x12@\n" +
	"\x1atoken_endpoint_auth_method\x18\x03 \x01(\tH\x01R\x17tokenEndpointAuthMethod\x88\x01\x01\x12\x1f\n" +
	"\vgrant_types\x18\x04 \x03(\tR\n" +
	"grantTypes\x12%\n" +
	"\x0eresponse_types\x18\x05 \x03(\tR\rresponseTypes\x12$\n" +
	"\vclient_name\x18\x06 \x01(\tH\x02R\n" +
	"clientName\x88\x01\x01\x12f\n" +
	"\x10client_name_i18n\x18\a \x03(\v2<.oidc.client.v1.ClientIDMetadataDocument.ClientNameI18nEntryR\x0eclientNameI18n\x12\"\n" +
	"\n" +
	"client_uri\x18\b \x01(\tH\x03R\tclientUri\x88\x01\x01\x12\x1e\n" +
	"\blogo_uri\x18\t \x01(\tH\x04R\alogoUri\x88\x01\x01\x12]\n" +
	"\rlogo_uri_i18n\x18\n" +
	" \x03(\v29.oidc.client.v1.ClientIDMetadataDocument.LogoUriI18nEntryR\vlogoUriI18n\x12\x19\n" +
	"\x05scope\x18\v \x01(\tH\x05R\x05scope\x88\x01\x01\x12\x1a\n" +
	"\bcontacts\x18\f \x03(\tR\bcontacts\x12\x1c\n" +
	"\atos_uri\x18\r \x01(\tH\x06R\x06tosUri\x88\x01\x01\x12Z\n" +
	"\ftos_uri_i18n\x18\x0e \x03(\v28.oidc.client.v1.ClientIDMetadataDocument.TosUriI18nEntryR\n" +
	"tosUriI18n\x12\"\n" +
	"\n" +
	"policy_uri\x18\x0f \x01(\tH\aR\tpolicyUri\x88\x01\x01\x12c\n" +
	"\x0fpolicy_uri_i18n\x18\x10 \x03(\v2;.oidc.client.v1.ClientIDMetadataDocument.PolicyUriI18nEntryR\rpolicyUriI18n\x12\x1e\n" +
	"\bjwks_uri\x18\x11 \x01(\tH\bR\ajwksUri\x88\x01\x01\x12\x17\n" +
	"\x04jwks\x18\x12 \x01(\fH\tR\x04jwks\x88\x01\x01\x12$\n" +
	"\vsoftware_id\x18\x13 \x01(\tH\n" +
	"R\n" +
	"softwareId\x88\x01\x01\x12.\n" +
	"\x10software_version\x18\x14 \x01(\tH\vR\x0fsoftwareVersion\x88\x01\x01\x122\n" +
	"\x12software_statement\x18\x15 \x01(\tH\fR\x11softwareStatement\x88\x01\x01\x12&\n" +
	"\fsubject_type\x18\x16 \x01(\tH\rR\vsubjectType\x88\x01\x01\x120\n" +
	"\x11sector_identifier\x18\x17 \x01(\tH\x0eR\x10sectorIdentifier\x88\x01\x01\x12%\n" +
	"\x0eresponse_modes\x18\x18 \x03(\tR\rresponseModes\x12V\n" +
	"%require_pushed_authorization_requests\x18\x19 \x01(\bH\x0fR\"requirePushedAuthorizationRequests\x88\x01\x01\x12F\n" +
	"\x1drequire_signed_request_object\x18\x1a \x01(\bH\x10R\x1arequireSignedRequestObject\x88\x01\x01\x12<\n" +
	"\x18dpop_bound_access_tokens\x18\x1b \x01(\bH\x11R\x15dpopBoundAccessTokens\x88\x01\x01\x12 \n" +
	"\tspiffe_id\x18\x1e \x01(\tH\x12R\bspiffeId\x88\x01\x01\x129\n" +
	"\x16spiffe_bundle_endpoint\x18\x1f \x01(\tH\x13R\x14spiffeBundleEndpoint\x88\x01\x01\x12(\n" +
	"\rclient_secret\x18\x1c \x01(\tH\x14R\fclientSecret\x88\x01\x01\x12<\n" +
	"\x18client_secret_expires_at\x18\x1d \x01(\x03H\x15R\x15clientSecretExpiresAt\x88\x01\x01\x1aA\n" +
	"\x13ClientNameI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10LogoUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fTosUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12PolicyUriI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_client_idB\x1d\n" +
	"\x1b_token_endpoint_auth_methodB\x0e\n" +
	"\f_client_nameB\r\n" +
	"\v_client_uriB\v\n" +
	"\t_logo_uriB\b\n" +
	"\x06_scopeB\n" +
	"\n" +
	"\b_tos_uriB\r\n" +
	"\v_policy_uriB\v\n" +
	"\t_jwks_uriB\a\n" +
	"\x05_jwksB\x0e\n" +
	"\f_software_idB\x13\n" +
	"\x11_software_versionB\x15\n" +
	"\x13_software_statementB\x0f\n" +
	"\r_subject_typeB\x14\n" +
	"\x12_sector_identifierB(\n" +
	"&_require_pushed_authorization_requestsB \n" +
	"\x1e_require_signed_request_objectB\x1b\n" +
	"\x19_dpop_bound_access_tokensB\f\n" +
	"\n" +
	"_spiffe_idB\x19\n" +
	"\x17_spiffe_bundle_endpointB\x10\n" +
	"\x0e_client_secretB\x1b\n" +
	"\x19_client_secret_expires_at\"4\n" +
	"\x11SoftwareStatement\x12\x1f\n" +
	"\vsoftware_id\x18\x01 \x01(\tR\n" +
	"softwareId*}\n" +
	"\n" +
	"ClientType\x12\x1b\n" +
	"\x17CLIENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CLIENT_TYPE_CONFIDENTIAL\x10\x01\x12\x1c\n" +
	"\x18CLIENT_TYPE_CREDENTIALED\x10\x02\x12\x16\n" +
	"\x12CLIENT_TYPE_PUBLIC\x10\x03*\xa8\x01\n" +
	"\rClientProfile\x12\x1e\n" +
	"\x1aCLIENT_PROFILE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCLIENT_PROFILE_WEB_APPLICATION\x10\x01\x12,\n" +
	"(CLIENT_PROFILE_BROWSER_BASED_APPLICATION\x10\x02\x12%\n" +
	"!CLIENT_PROFILE_NATIVE_APPLICATION\x10\x03B+Z)zntr.io/solid/api/oidc/client/v1;clientv1b\x06proto3"

var (
	file_oidc_client_v1_client_proto_rawDescOnce sync.Once
	file_oidc_client_v1_client_proto_rawDescData []byte
)

func file_oidc_client_v1_client_proto_rawDescGZIP() []byte {
	file_oidc_client_v1_client_proto_rawDescOnce.Do(func() {
		file_oidc_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_client_v1_client_proto_rawDesc), len(file_oidc_client_v1_client_proto_rawDesc)))
	})
	return file_oidc_client_v1_client_proto_rawDescData
}

var file_oidc_client_v1_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_oidc_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_oidc_client_v1_client_proto_goTypes = []any{
	(ClientType)(0),                  // 0: oidc.client.v1.ClientType
	(ClientProfile)(0),               // 1: oidc.client.v1.ClientProfile
	(*Client)(nil),                   // 2: oidc.client.v1.Client
	(*ClientMeta)(nil),               // 3: oidc.client.v1.ClientMeta
	(*ClientIDMetadataDocument)(nil), // 4: oidc.client.v1.ClientIDMetadataDocument
	(*SoftwareStatement)(nil),        // 5: oidc.client.v1.SoftwareStatement
	nil,                              // 6: oidc.client.v1.ClientMeta.ClientNameI18nEntry
	nil,                              // 7: oidc.client.v1.ClientMeta.LogoUriI18nEntry
	nil,                              // 8: oidc.client.v1.ClientMeta.TosUriI18nEntry
	nil,                              // 9: oidc.client.v1.ClientMeta.PolicyUriI18nEntry
	nil,                              // 10: oidc.client.v1.ClientIDMetadataDocument.ClientNameI18nEntry
	nil,                              // 11: oidc.client.v1.ClientIDMetadataDocument.LogoUriI18nEntry
	nil,                              // 12: oidc.client.v1.ClientIDMetadataDocument.TosUriI18nEntry
	nil,                              // 13: oidc.client.v1.ClientIDMetadataDocument.PolicyUriI18nEntry
}
var file_oidc_client_v1_client_proto_depIdxs = []int32{
	0,  // 0: oidc.client.v1.Client.client_type:type_name -> oidc.client.v1.ClientType
	6,  // 1: oidc.client.v1.ClientMeta.client_name_i18n:type_name -> oidc.client.v1.ClientMeta.ClientNameI18nEntry
	7,  // 2: oidc.client.v1.ClientMeta.logo_uri_i18n:type_name -> oidc.client.v1.ClientMeta.LogoUriI18nEntry
	8,  // 3: oidc.client.v1.ClientMeta.tos_uri_i18n:type_name -> oidc.client.v1.ClientMeta.TosUriI18nEntry
	9,  // 4: oidc.client.v1.ClientMeta.policy_uri_i18n:type_name -> oidc.client.v1.ClientMeta.PolicyUriI18nEntry
	10, // 5: oidc.client.v1.ClientIDMetadataDocument.client_name_i18n:type_name -> oidc.client.v1.ClientIDMetadataDocument.ClientNameI18nEntry
	11, // 6: oidc.client.v1.ClientIDMetadataDocument.logo_uri_i18n:type_name -> oidc.client.v1.ClientIDMetadataDocument.LogoUriI18nEntry
	12, // 7: oidc.client.v1.ClientIDMetadataDocument.tos_uri_i18n:type_name -> oidc.client.v1.ClientIDMetadataDocument.TosUriI18nEntry
	13, // 8: oidc.client.v1.ClientIDMetadataDocument.policy_uri_i18n:type_name -> oidc.client.v1.ClientIDMetadataDocument.PolicyUriI18nEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_oidc_client_v1_client_proto_init() }
func file_oidc_client_v1_client_proto_init() {
	if File_oidc_client_v1_client_proto != nil {
		return
	}
	file_oidc_client_v1_client_proto_msgTypes[1].OneofWrappers = []any{}
	file_oidc_client_v1_client_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_client_v1_client_proto_rawDesc), len(file_oidc_client_v1_client_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_client_v1_client_proto_goTypes,
		DependencyIndexes: file_oidc_client_v1_client_proto_depIdxs,
		EnumInfos:         file_oidc_client_v1_client_proto_enumTypes,
		MessageInfos:      file_oidc_client_v1_client_proto_msgTypes,
	}.Build()
	File_oidc_client_v1_client_proto = out.File
	file_oidc_client_v1_client_proto_goTypes = nil
	file_oidc_client_v1_client_proto_depIdxs = nil
}
