// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/client/v1/client_api.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "zntr.io/solid/api/oidc/core/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ClientSecret        *string                `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3,oneof" json:"client_secret,omitempty"`
	ClientAssertionType *string                `protobuf:"bytes,3,opt,name=client_assertion_type,json=clientAssertionType,proto3,oneof" json:"client_assertion_type,omitempty"`
	ClientAssertion     *string                `protobuf:"bytes,4,opt,name=client_assertion,json=clientAssertion,proto3,oneof" json:"client_assertion,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 3.2: client certificate
	// from the mutual TLS presentation layer (X.509-SVID), PEM-encoded.
	TlsClientCert *string `protobuf:"bytes,5,opt,name=tls_client_cert,json=tlsClientCert,proto3,oneof" json:"tls_client_cert,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 3.3: WIT-SVID carried in
	// the OAuth-Client-Attestation header.
	ClientAttestation *string `protobuf:"bytes,6,opt,name=client_attestation,json=clientAttestation,proto3,oneof" json:"client_attestation,omitempty"`
	// draft-ietf-oauth-spiffe-client-auth-02 section 3.3: attestation PoP JWT
	// carried in the OAuth-Client-Attestation-PoP header.
	ClientAttestationPop *string `protobuf:"bytes,7,opt,name=client_attestation_pop,json=clientAttestationPop,proto3,oneof" json:"client_attestation_pop,omitempty"`
	// draft-ietf-oauth-security-topics-update-03 section 2.1.2.2: the
	// receiving endpoint URI, used to enforce endpoint-exact client-assertion
	// audience validation (an assertion is accepted only for the endpoint it
	// was actually sent to, or for the authorization server's issuer
	// identifier).
	Endpoint      *string `protobuf:"bytes,8,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_api_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *AuthenticateRequest) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	return ""
}

func (x *AuthenticateRequest) GetClientAssertionType() string {
	if x != nil && x.ClientAssertionType != nil {
		return *x.ClientAssertionType
	}
	return ""
}

func (x *AuthenticateRequest) GetClientAssertion() string {
	if x != nil && x.ClientAssertion != nil {
		return *x.ClientAssertion
	}
	return ""
}

func (x *AuthenticateRequest) GetTlsClientCert() string {
	if x != nil && x.TlsClientCert != nil {
		return *x.TlsClientCert
	}
	return ""
}

func (x *AuthenticateRequest) GetClientAttestation() string {
	if x != nil && x.ClientAttestation != nil {
		return *x.ClientAttestation
	}
	return ""
}

func (x *AuthenticateRequest) GetClientAttestationPop() string {
	if x != nil && x.ClientAttestationPop != nil {
		return *x.ClientAttestationPop
	}
	return ""
}

func (x *AuthenticateRequest) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *v1.Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_api_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AuthenticateResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// https://tools.ietf.org/html/rfc7591#section-2
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ClientMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetMetadata() *ClientMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *v1.Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_client_v1_client_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_oidc_client_v1_client_api_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RegisterResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

var File_oidc_client_v1_client_api_proto protoreflect.FileDescriptor

const file_oidc_client_v1_client_api_proto_rawDesc = "" +
	"\n" +
	"\x1foidc/client/v1/client_api.proto\x12\x0eoidc.client.v1\x1a\x1boidc/client/v1/client.proto\x1a\x18oidc/core/v1/error.proto\"\xa9\x04\n" +
	"\x13AuthenticateRequest\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12(\n" +
	"\rclient_secret\x18\x02 \x01(\tH\x01R\fclientSecret\x88\x01\x01\x127\n" +
	"\x15client_assertion_type\x18\x03 \x01(\tH\x02R\x13clientAssertionType\x88\x01\x01\x12.\n" +
	"\x10client_assertion\x18\x04 \x01(\tH\x03R\x0fclientAssertion\x88\x01\x01\x12+\n" +
	"\x0ftls_client_cert\x18\x05 \x01(\tH\x04R\rtlsClientCert\x88\x01\x01\x122\n" +
	"\x12client_attestation\x18\x06 \x01(\tH\x05R\x11clientAttestation\x88\x01\x01\x129\n" +
	"\x16client_attestation_pop\x18\a \x01(\tH\x06R\x14clientAttestationPop\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\b \x01(\tH\aR\bendpoint\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\x10\n" +
	"\x0e_client_secretB\x18\n" +
	"\x16_client_assertion_typeB\x13\n" +
	"\x11_client_assertionB\x12\n" +
	"\x10_tls_client_certB\x15\n" +
	"\x13_client_attestationB\x19\n" +
	"\x17_client_attestation_popB\v\n" +
	"\t_endpoint\"q\n" +
	"\x14AuthenticateResponse\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.oidc.core.v1.ErrorR\x05error\x12.\n" +
	"\x06client\x18\x02 \x01(\v2\x16.oidc.client.v1.ClientR\x06client\"I\n" +
	"\x0fRegisterRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.oidc.client.v1.ClientMetaR\bmetadata\"m\n" +
	"\x10RegisterResponse\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.oidc.core.v1.ErrorR\x05error\x12.\n" +
	"\x06client\x18\x02 \x01(\v2\x16.oidc.client.v1.ClientR\x06client2z\n" +
	"\x1bClientAuthenticationService\x12[\n" +
	"\fAuthenticate\x12#.oidc.client.v1.AuthenticateRequest\x1a$.oidc.client.v1.AuthenticateResponse\"\x002l\n" +
	"\x19ClientRegistrationService\x12O\n" +
	"\bRegister\x12\x1f.oidc.client.v1.RegisterRequest\x1a .oidc.client.v1.RegisterResponse\"\x00B+Z)zntr.io/solid/api/oidc/client/v1;clientv1b\x06proto3"

var (
	file_oidc_client_v1_client_api_proto_rawDescOnce sync.Once
	file_oidc_client_v1_client_api_proto_rawDescData []byte
)

func file_oidc_client_v1_client_api_proto_rawDescGZIP() []byte {
	file_oidc_client_v1_client_api_proto_rawDescOnce.Do(func() {
		file_oidc_client_v1_client_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_client_v1_client_api_proto_rawDesc), len(file_oidc_client_v1_client_api_proto_rawDesc)))
	})
	return file_oidc_client_v1_client_api_proto_rawDescData
}

var file_oidc_client_v1_client_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_oidc_client_v1_client_api_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: oidc.client.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: oidc.client.v1.AuthenticateResponse
	(*RegisterRequest)(nil),      // 2: oidc.client.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 3: oidc.client.v1.RegisterResponse
	(*v1.Error)(nil),             // 4: oidc.core.v1.Error
	(*Client)(nil),               // 5: oidc.client.v1.Client
	(*ClientMeta)(nil),           // 6: oidc.client.v1.ClientMeta
}
var file_oidc_client_v1_client_api_proto_depIdxs = []int32{
	4, // 0: oidc.client.v1.AuthenticateResponse.error:type_name -> oidc.core.v1.Error
	5, // 1: oidc.client.v1.AuthenticateResponse.client:type_name -> oidc.client.v1.Client
	6, // 2: oidc.client.v1.RegisterRequest.metadata:type_name -> oidc.client.v1.ClientMeta
	4, // 3: oidc.client.v1.RegisterResponse.error:type_name -> oidc.core.v1.Error
	5, // 4: oidc.client.v1.RegisterResponse.client:type_name -> oidc.client.v1.Client
	0, // 5: oidc.client.v1.ClientAuthenticationService.Authenticate:input_type -> oidc.client.v1.AuthenticateRequest
	2, // 6: oidc.client.v1.ClientRegistrationService.Register:input_type -> oidc.client.v1.RegisterRequest
	1, // 7: oidc.client.v1.ClientAuthenticationService.Authenticate:output_type -> oidc.client.v1.AuthenticateResponse
	3, // 8: oidc.client.v1.ClientRegistrationService.Register:output_type -> oidc.client.v1.RegisterResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_oidc_client_v1_client_api_proto_init() }
func file_oidc_client_v1_client_api_proto_init() {
	if File_oidc_client_v1_client_api_proto != nil {
		return
	}
	file_oidc_client_v1_client_proto_init()
	file_oidc_client_v1_client_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_client_v1_client_api_proto_rawDesc), len(file_oidc_client_v1_client_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_oidc_client_v1_client_api_proto_goTypes,
		DependencyIndexes: file_oidc_client_v1_client_api_proto_depIdxs,
		MessageInfos:      file_oidc_client_v1_client_api_proto_msgTypes,
	}.Build()
	File_oidc_client_v1_client_api_proto = out.File
	file_oidc_client_v1_client_api_proto_goTypes = nil
	file_oidc_client_v1_client_api_proto_depIdxs = nil
}
