// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: oidc/core/v1/introspection_api.proto

package corev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenIntrospectionAPIClient is the client API for TokenIntrospectionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenIntrospectionAPIClient interface {
	Instrospect(ctx context.Context, in *TokenIntrospectionRequest, opts ...grpc.CallOption) (*TokenIntrospectionResponse, error)
}

type tokenIntrospectionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenIntrospectionAPIClient(cc grpc.ClientConnInterface) TokenIntrospectionAPIClient {
	return &tokenIntrospectionAPIClient{cc}
}

func (c *tokenIntrospectionAPIClient) Instrospect(ctx context.Context, in *TokenIntrospectionRequest, opts ...grpc.CallOption) (*TokenIntrospectionResponse, error) {
	out := new(TokenIntrospectionResponse)
	err := c.cc.Invoke(ctx, "/oidc.core.v1.TokenIntrospectionAPI/Instrospect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenIntrospectionAPIServer is the server API for TokenIntrospectionAPI service.
// All implementations must embed UnimplementedTokenIntrospectionAPIServer
// for forward compatibility
type TokenIntrospectionAPIServer interface {
	Instrospect(context.Context, *TokenIntrospectionRequest) (*TokenIntrospectionResponse, error)
	mustEmbedUnimplementedTokenIntrospectionAPIServer()
}

// UnimplementedTokenIntrospectionAPIServer must be embedded to have forward compatible implementations.
type UnimplementedTokenIntrospectionAPIServer struct {
}

func (UnimplementedTokenIntrospectionAPIServer) Instrospect(context.Context, *TokenIntrospectionRequest) (*TokenIntrospectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Instrospect not implemented")
}
func (UnimplementedTokenIntrospectionAPIServer) mustEmbedUnimplementedTokenIntrospectionAPIServer() {}

// UnsafeTokenIntrospectionAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenIntrospectionAPIServer will
// result in compilation errors.
type UnsafeTokenIntrospectionAPIServer interface {
	mustEmbedUnimplementedTokenIntrospectionAPIServer()
}

func RegisterTokenIntrospectionAPIServer(s grpc.ServiceRegistrar, srv TokenIntrospectionAPIServer) {
	s.RegisterService(&TokenIntrospectionAPI_ServiceDesc, srv)
}

func _TokenIntrospectionAPI_Instrospect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenIntrospectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenIntrospectionAPIServer).Instrospect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oidc.core.v1.TokenIntrospectionAPI/Instrospect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenIntrospectionAPIServer).Instrospect(ctx, req.(*TokenIntrospectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenIntrospectionAPI_ServiceDesc is the grpc.ServiceDesc for TokenIntrospectionAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenIntrospectionAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oidc.core.v1.TokenIntrospectionAPI",
	HandlerType: (*TokenIntrospectionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Instrospect",
			Handler:    _TokenIntrospectionAPI_Instrospect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oidc/core/v1/introspection_api.proto",
}
