// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/flow/v1/flow.proto

package flowv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "zntr.io/solid/api/oidc/token/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An Authentication Request is an OAuth 2.0 Authorization Request that requests
// that the End-User be authenticated by the Authorization Server.
type AuthorizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. OpenID Connect requests MUST contain the openid scope value. If
	// the openid scope value is not present, the behavior is entirely unspecified.
	// Other scope values MAY be present. Scope values used that are not understood
	// by an implementation SHOULD be ignored.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// REQUIRED. OAuth 2.0 Response Type value that determines the authorization
	// processing flow to be used, including what parameters are returned from
	// the endpoints used. When using the Authorization Code Flow, this value is
	// code.
	ResponseType string `protobuf:"bytes,2,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	// REQUIRED. OAuth 2.0 Client Identifier valid at the Authorization Server.
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// REQUIRED. Redirection URI to which the response will be sent. This URI
	// MUST exactly match one of the Redirection URI values for the Client
	// pre-registered at the OpenID Provider, with the matching performed as
	// described in Section 6.2.1 of [RFC3986] (Simple String Comparison).
	// When using this flow, the Redirection URI SHOULD use the https scheme;
	// however, it MAY use the http scheme, provided that the Client Type is
	// confidential, as defined in Section 2.1 of OAuth 2.0, and provided the OP
	// allows the use of http Redirection URIs in this case. The Redirection URI
	// MAY use an alternate scheme, such as one that is intended to identify a
	// callback into a native application.
	RedirectUri string `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	// RECOMMENDED. Opaque value used to maintain state between the request and
	// the callback. Typically, Cross-Site Request Forgery (CSRF, XSRF) mitigation
	// is done by cryptographically binding the value of this parameter with a
	// browser cookie.
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// OPTIONAL. Informs the Authorization Server of the mechanism to be used for
	// returning parameters from the Authorization Endpoint. This use of this
	// parameter is NOT RECOMMENDED when the Response Mode that would be requested
	// is the default mode specified for the Response Type.
	ResponseMode *string `protobuf:"bytes,6,opt,name=response_mode,json=responseMode,proto3,oneof" json:"response_mode,omitempty"`
	// OPTIONAL. String value used to associate a Client session with an ID Token,
	// and to mitigate replay attacks. The value is passed through unmodified from
	// the Authentication Request to the ID Token. Sufficient entropy MUST be
	// present in the nonce values used to prevent attackers from guessing values.
	// https://www.rfc-editor.org/rfc/rfc9700#section-4.5.3
	Nonce string `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// OPTIONAL. ASCII string value that specifies how the Authorization Server
	// displays the authentication and consent user interface pages to the End-User.
	Display *string `protobuf:"bytes,8,opt,name=display,proto3,oneof" json:"display,omitempty"`
	// OPTIONAL. Space delimited, case sensitive list of ASCII string values that
	// specifies whether the Authorization Server prompts the End-User for
	// reauthentication and consent.
	Prompt *string `protobuf:"bytes,9,opt,name=prompt,proto3,oneof" json:"prompt,omitempty"`
	// OPTIONAL. Maximum Authentication Age. Specifies the allowable elapsed time
	// in seconds since the last time the End-User was actively authenticated by
	// the OP. If the elapsed time is greater than this value, the OP MUST attempt
	// to actively re-authenticate the End-User. (The max_age request parameter
	// corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] max_auth_age request
	// parameter.) When max_age is used, the ID Token returned MUST include an
	// auth_time Claim Value.
	MaxAge *uint64 `protobuf:"varint,10,opt,name=max_age,json=maxAge,proto3,oneof" json:"max_age,omitempty"`
	// OPTIONAL. End-User's preferred languages and scripts for the user
	// interface, represented as a space-separated list of BCP47 [RFC5646]
	// language tag values, ordered by preference. For instance, the value "fr-CA
	// fr en" represents a preference for French as spoken in Canada, then French
	// (without a region designation), followed by English (without a region
	// designation). An error SHOULD NOT result if some or all of the requested
	// locales are not supported by the OpenID Provider.
	UiLocales *string `protobuf:"bytes,11,opt,name=ui_locales,json=uiLocales,proto3,oneof" json:"ui_locales,omitempty"`
	// OPTIONAL. ID Token previously issued by the Authorization Server being
	// passed as a hint about the End-User's current or past authenticated session
	// with the Client. If the End-User identified by the ID Token is logged in or
	// is logged in by the request, then the Authorization Server returns a
	// positive response; otherwise, it SHOULD return an error, such as
	// login_required. When possible, an id_token_hint SHOULD be present when
	// prompt=none is used and an invalid_request error MAY be returned if it is
	// not; however, the server SHOULD respond successfully when possible, even
	// if it is not present. The Authorization Server need not be listed as an
	// audience of the ID Token when it is used as an id_token_hint value.
	// If the ID Token received by the RP from the OP is encrypted, to use it as
	// an id_token_hint, the Client MUST decrypt the signed ID Token contained
	// within the encrypted ID Token. The Client MAY re-encrypt the signed ID
	// token to the Authentication Server using a key that enables the server to
	// decrypt the ID Token, and use the re-encrypted ID token as the
	// id_token_hint value.
	IdTokenHint *string `protobuf:"bytes,12,opt,name=id_token_hint,json=idTokenHint,proto3,oneof" json:"id_token_hint,omitempty"`
	// OPTIONAL. Requested Authentication Context Class Reference values.
	// Space-separated string that specifies the acr values that the Authorization
	// Server is being requested to use for processing this Authentication
	// Request, with the values appearing in order of preference. The
	// Authentication Context Class satisfied by the authentication performed is
	// returned as the acr Claim Value, as specified in Section 2. The acr Claim
	// is requested as a Voluntary Claim by this parameter.
	AcrValues *string `protobuf:"bytes,13,opt,name=acr_values,json=acrValues,proto3,oneof" json:"acr_values,omitempty"`
	// OPTIONAL. This parameter enables OpenID Connect requests to be passed in a
	// single, self-contained parameter and to be optionally signed and/or
	// encrypted. The parameter value is a Request Object value, as specified in
	// Section 6.1. It represents the request as a JWT whose Claims are the
	// request parameters.
	Request *string `protobuf:"bytes,14,opt,name=request,proto3,oneof" json:"request,omitempty"`
	// OPTIONAL. This parameter enables OpenID Connect requests to be passed by
	// reference, rather than by value. The request_uri value is a URL using the
	// https scheme referencing a resource containing a Request Object value,
	// which is a JWT containing the request parameters.
	RequestUri *string `protobuf:"bytes,15,opt,name=request_uri,json=requestUri,proto3,oneof" json:"request_uri,omitempty"`
	// REQUIRED. This parameter enables PKCE flow.
	CodeChallenge string `protobuf:"bytes,16,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	// REQUIRED. This parameter enables PKCE flow.
	CodeChallengeMethod string `protobuf:"bytes,17,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"`
	// REQUIRED. Add targeted audience.
	Audience string `protobuf:"bytes,18,opt,name=audience,proto3" json:"audience,omitempty"`
	// OPTIONAL.
	// https://www.rfc-editor.org/rfc/rfc9449#section-5
	DpopProof *string `protobuf:"bytes,19,opt,name=dpop_proof,json=dpopProof,proto3,oneof" json:"dpop_proof,omitempty"`
	// OPTIONAL. Authorization Code Binding to a DPoP Key: the JWK thumbprint
	// (RFC 7638) of the DPoP key the client will use at the token endpoint.
	// When present, the authorization code is issued bound to this key and
	// redemption MUST present a DPoP proof made with the same key.
	// https://www.rfc-editor.org/rfc/rfc9449#section-10
	DpopJkt *string `protobuf:"bytes,24,opt,name=dpop_jkt,json=dpopJkt,proto3,oneof" json:"dpop_jkt,omitempty"`
	// OPTIONAL
	// https://tools.ietf.org/html/rfc8707
	// Indicates the target service or resource to which access is being
	// requested.  Its value MUST be an absolute URI, as specified by
	// Section 4.3 of [RFC3986].  The URI MUST NOT include a fragment
	// component.  It SHOULD NOT include a query component, but it is
	// recognized that there are cases that make a query component a
	// useful and necessary part of the resource parameter, such as when
	// one or more query parameters are used to scope requests to an
	// application.  The "resource" parameter URI value is an identifier
	// representing the identity of the resource, which MAY be a locator
	// that corresponds to a network-addressable location where the
	// target resource is hosted.  Multiple "resource" parameters MAY be
	// used to indicate that the requested token is intended to be used
	// at multiple resources.
	Resource []string `protobuf:"bytes,20,rep,name=resource,proto3" json:"resource,omitempty"`
	// OPTIONAL.
	// Issuer url used for JARM decoding.
	Iss *string `protobuf:"bytes,21,opt,name=iss,proto3,oneof" json:"iss,omitempty"`
	// OPTIONAL. A token containing information identifying the end-user for whom
	// authentication is being requested. The particular details and security
	// requirements for the login_hint_token as well as how the end-user is
	// identified by its content are deployment or profile specific.
	LoginHintToken *string `protobuf:"bytes,22,opt,name=login_hint_token,json=loginHintToken,proto3,oneof" json:"login_hint_token,omitempty"`
	// OPTIONAL. A hint to the OpenID Provider regarding the end-user for whom
	// authentication is being requested. The value may contain an email address,
	// phone number, account number, subject identifier, username, etc., which
	// identifies the end-user to the OP. The value may be directly collected from
	// the user by the Client before requesting authentication at the OP, for
	// example, but may also be obtained by other means.
	LoginHint *string `protobuf:"bytes,23,opt,name=login_hint,json=loginHint,proto3,oneof" json:"login_hint,omitempty"`
	// OPTIONAL. JSON array of objects. Each object holds the requested
	// permissions or other details for a specific resource or set of
	// resources. The array is the unit of retrieval: authorization_details
	// are only carried as request-object claims (JAR) in this profile, so
	// the parameter is accepted when the request object carries it.
	// https://www.rfc-editor.org/rfc/rfc9396#section-3
	AuthorizationDetails []*v1.AuthorizationDetail `protobuf:"bytes,25,rep,name=authorization_details,json=authorizationDetails,proto3" json:"authorization_details,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_oidc_flow_v1_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizationRequest) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizationRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizationRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizationRequest) GetResponseMode() string {
	if x != nil && x.ResponseMode != nil {
		return *x.ResponseMode
	}
	return ""
}

func (x *AuthorizationRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthorizationRequest) GetDisplay() string {
	if x != nil && x.Display != nil {
		return *x.Display
	}
	return ""
}

func (x *AuthorizationRequest) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *AuthorizationRequest) GetMaxAge() uint64 {
	if x != nil && x.MaxAge != nil {
		return *x.MaxAge
	}
	return 0
}

func (x *AuthorizationRequest) GetUiLocales() string {
	if x != nil && x.UiLocales != nil {
		return *x.UiLocales
	}
	return ""
}

func (x *AuthorizationRequest) GetIdTokenHint() string {
	if x != nil && x.IdTokenHint != nil {
		return *x.IdTokenHint
	}
	return ""
}

func (x *AuthorizationRequest) GetAcrValues() string {
	if x != nil && x.AcrValues != nil {
		return *x.AcrValues
	}
	return ""
}

func (x *AuthorizationRequest) GetRequest() string {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return ""
}

func (x *AuthorizationRequest) GetRequestUri() string {
	if x != nil && x.RequestUri != nil {
		return *x.RequestUri
	}
	return ""
}

func (x *AuthorizationRequest) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizationRequest) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizationRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AuthorizationRequest) GetDpopProof() string {
	if x != nil && x.DpopProof != nil {
		return *x.DpopProof
	}
	return ""
}

func (x *AuthorizationRequest) GetDpopJkt() string {
	if x != nil && x.DpopJkt != nil {
		return *x.DpopJkt
	}
	return ""
}

func (x *AuthorizationRequest) GetResource() []string {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AuthorizationRequest) GetIss() string {
	if x != nil && x.Iss != nil {
		return *x.Iss
	}
	return ""
}

func (x *AuthorizationRequest) GetLoginHintToken() string {
	if x != nil && x.LoginHintToken != nil {
		return *x.LoginHintToken
	}
	return ""
}

func (x *AuthorizationRequest) GetLoginHint() string {
	if x != nil && x.LoginHint != nil {
		return *x.LoginHint
	}
	return ""
}

func (x *AuthorizationRequest) GetAuthorizationDetails() []*v1.AuthorizationDetail {
	if x != nil {
		return x.AuthorizationDetails
	}
	return nil
}

var File_oidc_flow_v1_flow_proto protoreflect.FileDescriptor

const file_oidc_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x17oidc/flow/v1/flow.proto\x12\foidc.flow.v1\x1a\x1bbuf/validate/validate.proto\x1a(oidc/token/v1/authorization_detail.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xda\b\n" +
	"\x14AuthorizationRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12#\n" +
	"\rresponse_type\x18\x02 \x01(\tR\fresponseType\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12(\n" +
	"\rresponse_mode\x18\x06 \x01(\tH\x00R\fresponseMode\x88\x01\x01\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x1d\n" +
	"\adisplay\x18\b \x01(\tH\x01R\adisplay\x88\x01\x01\x12\x1b\n" +
	"\x06prompt\x18\t \x01(\tH\x02R\x06prompt\x88\x01\x01\x12\x1c\n" +
	"\amax_age\x18\n" +
	" \x01(\x04H\x03R\x06maxAge\x88\x01\x01\x12\"\n" +
	"\n" +
	"ui_locales\x18\v \x01(\tH\x04R\tuiLocales\x88\x01\x01\x12'\n" +
	"\rid_token_hint\x18\f \x01(\tH\x05R\vidTokenHint\x88\x01\x01\x12\"\n" +
	"\n" +
	"acr_values\x18\r \x01(\tH\x06R\tacrValues\x88\x01\x01\x12\x1d\n" +
	"\arequest\x18\x0e \x01(\tH\aR\arequest\x88\x01\x01\x12$\n" +
	"\vrequest_uri\x18\x0f \x01(\tH\bR\n" +
	"requestUri\x88\x01\x01\x12%\n" +
	"\x0ecode_challenge\x18\x10 \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\x11 \x01(\tR\x13codeChallengeMethod\x12\x1a\n" +
	"\baudience\x18\x12 \x01(\tR\baudience\x12\"\n" +
	"\n" +
	"dpop_proof\x18\x13 \x01(\tH\tR\tdpopProof\x88\x01\x01\x12\x1e\n" +
	"\bdpop_jkt\x18\x18 \x01(\tH\n" +
	"R\adpopJkt\x88\x01\x01\x12\x1a\n" +
	"\bresource\x18\x14 \x03(\tR\bresource\x12\x15\n" +
	"\x03iss\x18\x15 \x01(\tH\vR\x03iss\x88\x01\x01\x12-\n" +
	"\x10login_hint_token\x18\x16 \x01(\tH\fR\x0eloginHintToken\x88\x01\x01\x12\"\n" +
	"\n" +
	"login_hint\x18\x17 \x01(\tH\rR\tloginHint\x88\x01\x01\x12W\n" +
	"\x15authorization_details\x18\x19 \x03(\v2\".oidc.token.v1.AuthorizationDetailR\x14authorizationDetailsB\x10\n" +
	"\x0e_response_modeB\n" +
	"\n" +
	"\b_displayB\t\n" +
	"\a_promptB\n" +
	"\n" +
	"\b_max_ageB\r\n" +
	"\v_ui_localesB\x10\n" +
	"\x0e_id_token_hintB\r\n" +
	"\v_acr_valuesB\n" +
	"\n" +
	"\b_requestB\x0e\n" +
	"\f_request_uriB\r\n" +
	"\v_dpop_proofB\v\n" +
	"\t_dpop_jktB\x06\n" +
	"\x04_issB\x13\n" +
	"\x11_login_hint_tokenB\r\n" +
	"\v_login_hintB'Z%zntr.io/solid/api/oidc/flow/v1;flowv1b\x06proto3"

var (
	file_oidc_flow_v1_flow_proto_rawDescOnce sync.Once
	file_oidc_flow_v1_flow_proto_rawDescData []byte
)

func file_oidc_flow_v1_flow_proto_rawDescGZIP() []byte {
	file_oidc_flow_v1_flow_proto_rawDescOnce.Do(func() {
		file_oidc_flow_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_flow_v1_flow_proto_rawDesc), len(file_oidc_flow_v1_flow_proto_rawDesc)))
	})
	return file_oidc_flow_v1_flow_proto_rawDescData
}

var file_oidc_flow_v1_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oidc_flow_v1_flow_proto_goTypes = []any{
	(*AuthorizationRequest)(nil),   // 0: oidc.flow.v1.AuthorizationRequest
	(*v1.AuthorizationDetail)(nil), // 1: oidc.token.v1.AuthorizationDetail
}
var file_oidc_flow_v1_flow_proto_depIdxs = []int32{
	1, // 0: oidc.flow.v1.AuthorizationRequest.authorization_details:type_name -> oidc.token.v1.AuthorizationDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oidc_flow_v1_flow_proto_init() }
func file_oidc_flow_v1_flow_proto_init() {
	if File_oidc_flow_v1_flow_proto != nil {
		return
	}
	file_oidc_flow_v1_flow_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_flow_v1_flow_proto_rawDesc), len(file_oidc_flow_v1_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_oidc_flow_v1_flow_proto_depIdxs,
		MessageInfos:      file_oidc_flow_v1_flow_proto_msgTypes,
	}.Build()
	File_oidc_flow_v1_flow_proto = out.File
	file_oidc_flow_v1_flow_proto_goTypes = nil
	file_oidc_flow_v1_flow_proto_depIdxs = nil
}
