// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/flow/v1/token_grant.proto

package flowv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantAuthorizationCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. The authorization code issued for this request.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// REQUIRED. Redirection URI as registered by the client.
	RedirectUri string `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	// REQUIRED. PKCE code verifier.
	CodeVerifier string `protobuf:"bytes,3,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	// OPTIONAL. Authorization Code Binding to DPoP Key.
	// https://www.rfc-editor.org/rfc/rfc9449#section-10
	DpopJkt       *string `protobuf:"bytes,4,opt,name=dpop_jkt,json=dpopJkt,proto3,oneof" json:"dpop_jkt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAuthorizationCode) Reset() {
	*x = GrantAuthorizationCode{}
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAuthorizationCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAuthorizationCode) ProtoMessage() {}

func (x *GrantAuthorizationCode) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAuthorizationCode.ProtoReflect.Descriptor instead.
func (*GrantAuthorizationCode) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{0}
}

func (x *GrantAuthorizationCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GrantAuthorizationCode) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GrantAuthorizationCode) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

func (x *GrantAuthorizationCode) GetDpopJkt() string {
	if x != nil && x.DpopJkt != nil {
		return *x.DpopJkt
	}
	return ""
}

type GrantRefreshToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. The refresh token to exchange.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRefreshToken) Reset() {
	*x = GrantRefreshToken{}
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRefreshToken) ProtoMessage() {}

func (x *GrantRefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRefreshToken.ProtoReflect.Descriptor instead.
func (*GrantRefreshToken) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{1}
}

func (x *GrantRefreshToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// https://tools.ietf.org/html/rfc8628#section-3.4
type GrantDeviceCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED.  The device verification code, "device_code" from the
	// device authorization response, defined in Section 3.2.
	DeviceCode string `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	// REQUIRED if the client is not authenticating with the
	// authorization server as described in Section 3.2.1. of [RFC6749].
	// The client identifier as described in Section 2.2 of [RFC6749].
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantDeviceCode) Reset() {
	*x = GrantDeviceCode{}
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantDeviceCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantDeviceCode) ProtoMessage() {}

func (x *GrantDeviceCode) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantDeviceCode.ProtoReflect.Descriptor instead.
func (*GrantDeviceCode) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{2}
}

func (x *GrantDeviceCode) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *GrantDeviceCode) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GrantClientCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantClientCredentials) Reset() {
	*x = GrantClientCredentials{}
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantClientCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantClientCredentials) ProtoMessage() {}

func (x *GrantClientCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantClientCredentials.ProtoReflect.Descriptor instead.
func (*GrantClientCredentials) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{3}
}

// https://tools.ietf.org/html/rfc8693#section-2.1
type GrantTokenExchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OPTIONAL.  An identifier, as described in Section 3, for the type
	// of the requested security token.  If the requested type is
	// unspecified, the issued token type is at the discretion of the
	// authorization server and may be dictated by knowledge of the
	// requirements of the service or resource indicated by the
	// "resource" or "audience" parameter.
	RequestedTokenType *string `protobuf:"bytes,1,opt,name=requested_token_type,json=requestedTokenType,proto3,oneof" json:"requested_token_type,omitempty"`
	// REQUIRED.  A security token that represents the identity of the
	// party on behalf of whom the request is being made.  Typically, the
	// subject of this token will be the subject of the security token
	// issued in response to the request.
	SubjectToken string `protobuf:"bytes,2,opt,name=subject_token,json=subjectToken,proto3" json:"subject_token,omitempty"`
	// REQUIRED.  An identifier, as described in Section 3, that
	// indicates the type of the security token in the "subject_token"
	// parameter.
	SubjectTokenType string `protobuf:"bytes,3,opt,name=subject_token_type,json=subjectTokenType,proto3" json:"subject_token_type,omitempty"`
	// OPTIONAL.  A security token that represents the identity of the
	// acting party.  Typically, this will be the party that is
	// authorized to use the requested security token and act on behalf
	// of the subject.
	ActorToken *string `protobuf:"bytes,4,opt,name=actor_token,json=actorToken,proto3,oneof" json:"actor_token,omitempty"`
	// An identifier, as described in Section 3, that indicates the type
	// of the security token in the "actor_token" parameter.  This is
	// REQUIRED when the "actor_token" parameter is present in the
	// request but MUST NOT be included otherwise.
	ActorTokenType *string `protobuf:"bytes,5,opt,name=actor_token_type,json=actorTokenType,proto3,oneof" json:"actor_token_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrantTokenExchange) Reset() {
	*x = GrantTokenExchange{}
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTokenExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTokenExchange) ProtoMessage() {}

func (x *GrantTokenExchange) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTokenExchange.ProtoReflect.Descriptor instead.
func (*GrantTokenExchange) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{4}
}

func (x *GrantTokenExchange) GetRequestedTokenType() string {
	if x != nil && x.RequestedTokenType != nil {
		return *x.RequestedTokenType
	}
	return ""
}

func (x *GrantTokenExchange) GetSubjectToken() string {
	if x != nil {
		return x.SubjectToken
	}
	return ""
}

func (x *GrantTokenExchange) GetSubjectTokenType() string {
	if x != nil {
		return x.SubjectTokenType
	}
	return ""
}

func (x *GrantTokenExchange) GetActorToken() string {
	if x != nil && x.ActorToken != nil {
		return *x.ActorToken
	}
	return ""
}

func (x *GrantTokenExchange) GetActorTokenType() string {
	if x != nil && x.ActorTokenType != nil {
		return *x.ActorTokenType
	}
	return ""
}

var File_oidc_flow_v1_token_grant_proto protoreflect.FileDescriptor

const file_oidc_flow_v1_token_grant_proto_rawDesc = "" +
	"\n" +
	"\x1eoidc/flow/v1/token_grant.proto\x12\foidc.flow.v1\x1a\x1bbuf/validate/validate.proto\"\xe4\x01\n" +
	"\x16GrantAuthorizationCode\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\bR\x04code\x120\n" +
	"\fredirect_uri\x18\x02 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x01\x18\x80\x10\x88\x01\x01R\vredirectUri\x12K\n" +
	"\rcode_verifier\x18\x03 \x01(\tB&\xbaH#r!\x10+\x18\x80\x012\x1a^[A-Za-z0-9\\-._~]{43,128}$R\fcodeVerifier\x12\x1e\n" +
	"\bdpop_jkt\x18\x04 \x01(\tH\x00R\adpopJkt\x88\x01\x01B\v\n" +
	"\t_dpop_jkt\"D\n" +
	"\x11GrantRefreshToken\x12/\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\frefreshToken\"g\n" +
	"\x0fGrantDeviceCode\x12+\n" +
	"\vdevice_code\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\n" +
	"deviceCode\x12'\n" +
	"\tclient_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\bclientId\"\x18\n" +
	"\x16GrantClientCredentials\"\xc9\x02\n" +
	"\x12GrantTokenExchange\x125\n" +
	"\x14requested_token_type\x18\x01 \x01(\tH\x00R\x12requestedTokenType\x88\x01\x01\x12/\n" +
	"\rsubject_token\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\fsubjectToken\x128\n" +
	"\x12subject_token_type\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x10subjectTokenType\x12$\n" +
	"\vactor_token\x18\x04 \x01(\tH\x01R\n" +
	"actorToken\x88\x01\x01\x12-\n" +
	"\x10actor_token_type\x18\x05 \x01(\tH\x02R\x0eactorTokenType\x88\x01\x01B\x17\n" +
	"\x15_requested_token_typeB\x0e\n" +
	"\f_actor_tokenB\x13\n" +
	"\x11_actor_token_typeB'Z%zntr.io/solid/api/oidc/flow/v1;flowv1b\x06proto3"

var (
	file_oidc_flow_v1_token_grant_proto_rawDescOnce sync.Once
	file_oidc_flow_v1_token_grant_proto_rawDescData []byte
)

func file_oidc_flow_v1_token_grant_proto_rawDescGZIP() []byte {
	file_oidc_flow_v1_token_grant_proto_rawDescOnce.Do(func() {
		file_oidc_flow_v1_token_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_flow_v1_token_grant_proto_rawDesc), len(file_oidc_flow_v1_token_grant_proto_rawDesc)))
	})
	return file_oidc_flow_v1_token_grant_proto_rawDescData
}

var file_oidc_flow_v1_token_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_oidc_flow_v1_token_grant_proto_goTypes = []any{
	(*GrantAuthorizationCode)(nil), // 0: oidc.flow.v1.GrantAuthorizationCode
	(*GrantRefreshToken)(nil),      // 1: oidc.flow.v1.GrantRefreshToken
	(*GrantDeviceCode)(nil),        // 2: oidc.flow.v1.GrantDeviceCode
	(*GrantClientCredentials)(nil), // 3: oidc.flow.v1.GrantClientCredentials
	(*GrantTokenExchange)(nil),     // 4: oidc.flow.v1.GrantTokenExchange
}
var file_oidc_flow_v1_token_grant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oidc_flow_v1_token_grant_proto_init() }
func file_oidc_flow_v1_token_grant_proto_init() {
	if File_oidc_flow_v1_token_grant_proto != nil {
		return
	}
	file_oidc_flow_v1_token_grant_proto_msgTypes[0].OneofWrappers = []any{}
	file_oidc_flow_v1_token_grant_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_flow_v1_token_grant_proto_rawDesc), len(file_oidc_flow_v1_token_grant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_flow_v1_token_grant_proto_goTypes,
		DependencyIndexes: file_oidc_flow_v1_token_grant_proto_depIdxs,
		MessageInfos:      file_oidc_flow_v1_token_grant_proto_msgTypes,
	}.Build()
	File_oidc_flow_v1_token_grant_proto = out.File
	file_oidc_flow_v1_token_grant_proto_goTypes = nil
	file_oidc_flow_v1_token_grant_proto_depIdxs = nil
}
