// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: oidc/flow/v1/token_grant.proto

package flowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantAuthorizationCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri  string `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	CodeVerifier string `protobuf:"bytes,3,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	// OPTIONAL. Authorization Code Binding to DPoP Key.
	// https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-09#section-10
	DpopJkt *string `protobuf:"bytes,4,opt,name=dpop_jkt,json=dpopJkt,proto3,oneof" json:"dpop_jkt,omitempty"`
}

func (x *GrantAuthorizationCode) Reset() {
	*x = GrantAuthorizationCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantAuthorizationCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAuthorizationCode) ProtoMessage() {}

func (x *GrantAuthorizationCode) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAuthorizationCode.ProtoReflect.Descriptor instead.
func (*GrantAuthorizationCode) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{0}
}

func (x *GrantAuthorizationCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GrantAuthorizationCode) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GrantAuthorizationCode) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

func (x *GrantAuthorizationCode) GetDpopJkt() string {
	if x != nil && x.DpopJkt != nil {
		return *x.DpopJkt
	}
	return ""
}

type GrantRefreshToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *GrantRefreshToken) Reset() {
	*x = GrantRefreshToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantRefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRefreshToken) ProtoMessage() {}

func (x *GrantRefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRefreshToken.ProtoReflect.Descriptor instead.
func (*GrantRefreshToken) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{1}
}

func (x *GrantRefreshToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// https://tools.ietf.org/html/rfc8628#section-3.4
type GrantDeviceCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// REQUIRED.  The device verification code, "device_code" from the
	// device authorization response, defined in Section 3.2.
	DeviceCode string `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	// REQUIRED if the client is not authenticating with the
	// authorization server as described in Section 3.2.1. of [RFC6749].
	// The client identifier as described in Section 2.2 of [RFC6749].
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *GrantDeviceCode) Reset() {
	*x = GrantDeviceCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantDeviceCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantDeviceCode) ProtoMessage() {}

func (x *GrantDeviceCode) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantDeviceCode.ProtoReflect.Descriptor instead.
func (*GrantDeviceCode) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{2}
}

func (x *GrantDeviceCode) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *GrantDeviceCode) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GrantClientCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GrantClientCredentials) Reset() {
	*x = GrantClientCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantClientCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantClientCredentials) ProtoMessage() {}

func (x *GrantClientCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantClientCredentials.ProtoReflect.Descriptor instead.
func (*GrantClientCredentials) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{3}
}

// https://tools.ietf.org/html/rfc8693#section-2.1
type GrantTokenExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// OPTIONAL.  An identifier, as described in Section 3, for the type
	// of the requested security token.  If the requested type is
	// unspecified, the issued token type is at the discretion of the
	// authorization server and may be dictated by knowledge of the
	// requirements of the service or resource indicated by the
	// "resource" or "audience" parameter.
	RequestedTokenType *string `protobuf:"bytes,1,opt,name=requested_token_type,json=requestedTokenType,proto3,oneof" json:"requested_token_type,omitempty"`
	// REQUIRED.  A security token that represents the identity of the
	// party on behalf of whom the request is being made.  Typically, the
	// subject of this token will be the subject of the security token
	// issued in response to the request.
	SubjectToken string `protobuf:"bytes,2,opt,name=subject_token,json=subjectToken,proto3" json:"subject_token,omitempty"`
	// REQUIRED.  An identifier, as described in Section 3, that
	// indicates the type of the security token in the "subject_token"
	// parameter.
	SubjectTokenType string `protobuf:"bytes,3,opt,name=subject_token_type,json=subjectTokenType,proto3" json:"subject_token_type,omitempty"`
	// OPTIONAL.  A security token that represents the identity of the
	// acting party.  Typically, this will be the party that is
	// authorized to use the requested security token and act on behalf
	// of the subject.
	ActorToken *string `protobuf:"bytes,4,opt,name=actor_token,json=actorToken,proto3,oneof" json:"actor_token,omitempty"`
	// An identifier, as described in Section 3, that indicates the type
	// of the security token in the "actor_token" parameter.  This is
	// REQUIRED when the "actor_token" parameter is present in the
	// request but MUST NOT be included otherwise.
	ActorTokenType *string `protobuf:"bytes,5,opt,name=actor_token_type,json=actorTokenType,proto3,oneof" json:"actor_token_type,omitempty"`
}

func (x *GrantTokenExchange) Reset() {
	*x = GrantTokenExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantTokenExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTokenExchange) ProtoMessage() {}

func (x *GrantTokenExchange) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_flow_v1_token_grant_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTokenExchange.ProtoReflect.Descriptor instead.
func (*GrantTokenExchange) Descriptor() ([]byte, []int) {
	return file_oidc_flow_v1_token_grant_proto_rawDescGZIP(), []int{4}
}

func (x *GrantTokenExchange) GetRequestedTokenType() string {
	if x != nil && x.RequestedTokenType != nil {
		return *x.RequestedTokenType
	}
	return ""
}

func (x *GrantTokenExchange) GetSubjectToken() string {
	if x != nil {
		return x.SubjectToken
	}
	return ""
}

func (x *GrantTokenExchange) GetSubjectTokenType() string {
	if x != nil {
		return x.SubjectTokenType
	}
	return ""
}

func (x *GrantTokenExchange) GetActorToken() string {
	if x != nil && x.ActorToken != nil {
		return *x.ActorToken
	}
	return ""
}

func (x *GrantTokenExchange) GetActorTokenType() string {
	if x != nil && x.ActorTokenType != nil {
		return *x.ActorTokenType
	}
	return ""
}

var File_oidc_flow_v1_token_grant_proto protoreflect.FileDescriptor

var file_oidc_flow_v1_token_grant_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x69, 0x64, 0x63, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x22, 0xa1,
	0x01, 0x0a, 0x16, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x08, 0x64, 0x70, 0x6f, 0x70, 0x5f, 0x6a, 0x6b,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x70, 0x6f, 0x70, 0x4a,
	0x6b, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x70, 0x6f, 0x70, 0x5f, 0x6a,
	0x6b, 0x74, 0x22, 0x38, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4f, 0x0a, 0x0f,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x18, 0x0a,
	0x16, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0xb1, 0x02, 0x0a, 0x12, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x35,
	0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x12,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2d,
	0x0a, 0x10, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x17, 0x0a,
	0x15, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x9c, 0x01, 0x0a, 0x10,
	0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x42, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x25, 0x7a, 0x6e, 0x74, 0x72, 0x2e, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c,
	0x69, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x69, 0x64, 0x63, 0x2f, 0x66, 0x6c, 0x6f, 0x77,
	0x2f, 0x76, 0x31, 0x3b, 0x66, 0x6c, 0x6f, 0x77, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x46, 0x58,
	0xaa, 0x02, 0x0c, 0x4f, 0x69, 0x64, 0x63, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0c, 0x4f, 0x69, 0x64, 0x63, 0x5c, 0x46, 0x6c, 0x6f, 0x77, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x18, 0x4f, 0x69, 0x64, 0x63, 0x5c, 0x46, 0x6c, 0x6f, 0x77, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0e, 0x4f, 0x69, 0x64, 0x63,
	0x3a, 0x3a, 0x46, 0x6c, 0x6f, 0x77, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_oidc_flow_v1_token_grant_proto_rawDescOnce sync.Once
	file_oidc_flow_v1_token_grant_proto_rawDescData = file_oidc_flow_v1_token_grant_proto_rawDesc
)

func file_oidc_flow_v1_token_grant_proto_rawDescGZIP() []byte {
	file_oidc_flow_v1_token_grant_proto_rawDescOnce.Do(func() {
		file_oidc_flow_v1_token_grant_proto_rawDescData = protoimpl.X.CompressGZIP(file_oidc_flow_v1_token_grant_proto_rawDescData)
	})
	return file_oidc_flow_v1_token_grant_proto_rawDescData
}

var file_oidc_flow_v1_token_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_oidc_flow_v1_token_grant_proto_goTypes = []interface{}{
	(*GrantAuthorizationCode)(nil), // 0: oidc.flow.v1.GrantAuthorizationCode
	(*GrantRefreshToken)(nil),      // 1: oidc.flow.v1.GrantRefreshToken
	(*GrantDeviceCode)(nil),        // 2: oidc.flow.v1.GrantDeviceCode
	(*GrantClientCredentials)(nil), // 3: oidc.flow.v1.GrantClientCredentials
	(*GrantTokenExchange)(nil),     // 4: oidc.flow.v1.GrantTokenExchange
}
var file_oidc_flow_v1_token_grant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oidc_flow_v1_token_grant_proto_init() }
func file_oidc_flow_v1_token_grant_proto_init() {
	if File_oidc_flow_v1_token_grant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oidc_flow_v1_token_grant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantAuthorizationCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oidc_flow_v1_token_grant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantRefreshToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oidc_flow_v1_token_grant_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantDeviceCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oidc_flow_v1_token_grant_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantClientCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oidc_flow_v1_token_grant_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantTokenExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oidc_flow_v1_token_grant_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_oidc_flow_v1_token_grant_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oidc_flow_v1_token_grant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_flow_v1_token_grant_proto_goTypes,
		DependencyIndexes: file_oidc_flow_v1_token_grant_proto_depIdxs,
		MessageInfos:      file_oidc_flow_v1_token_grant_proto_msgTypes,
	}.Build()
	File_oidc_flow_v1_token_grant_proto = out.File
	file_oidc_flow_v1_token_grant_proto_rawDesc = nil
	file_oidc_flow_v1_token_grant_proto_goTypes = nil
	file_oidc_flow_v1_token_grant_proto_depIdxs = nil
}
