// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/sdtoken/sdjwt (interfaces: Issuer)
//
// Generated by this command:
//
//	mockgen -destination sdk/sdtoken/sdjwt/mock/issuer.gen.go -package mock zntr.io/solid/sdk/sdtoken/sdjwt Issuer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	sdjwt "zntr.io/solid/sdk/sdtoken/sdjwt"
)

// MockIssuer is a mock of Issuer interface.
type MockIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockIssuerMockRecorder
	isgomock struct{}
}

// MockIssuerMockRecorder is the mock recorder for MockIssuer.
type MockIssuerMockRecorder struct {
	mock *MockIssuer
}

// NewMockIssuer creates a new mock instance.
func NewMockIssuer(ctrl *gomock.Controller) *MockIssuer {
	mock := &MockIssuer{ctrl: ctrl}
	mock.recorder = &MockIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuer) EXPECT() *MockIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockIssuer) Issue(ctx context.Context, claims map[string]any, opts ...sdjwt.IssueOption) (string, []string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, claims}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Issue", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Issue indicates an expected call of Issue.
func (mr *MockIssuerMockRecorder) Issue(ctx, claims any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, claims}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockIssuer)(nil).Issue), varargs...)
}
