// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/profile (interfaces: Server)
//
// Generated by this command:
//
//	mockgen -destination mock/server.gen.go -package mock zntr.io/solid/server/profile Server
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	profile "zntr.io/solid/server/profile"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// ApplicationType mocks base method.
func (m *MockServer) ApplicationType(name string) (profile.Client, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationType", name)
	ret0, _ := ret[0].(profile.Client)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ApplicationType indicates an expected call of ApplicationType.
func (mr *MockServerMockRecorder) ApplicationType(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationType", reflect.TypeOf((*MockServer)(nil).ApplicationType), name)
}
