// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/jwsreq (interfaces: AuthorizationEncoder)
//
// Generated by this command:
//
//	mockgen -destination mock/authorization_encoder.gen.go -package mock zntr.io/solid/sdk/jwsreq AuthorizationEncoder
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "go.uber.org/mock/gomock"
	reflect "reflect"

	flowv1 "zntr.io/solid/api/oidc/flow/v1"
)

// MockAuthorizationEncoder is a mock of AuthorizationEncoder interface.
type MockAuthorizationEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationEncoderMockRecorder
	isgomock struct{}
}

// MockAuthorizationEncoderMockRecorder is the mock recorder for MockAuthorizationEncoder.
type MockAuthorizationEncoderMockRecorder struct {
	mock *MockAuthorizationEncoder
}

// NewMockAuthorizationEncoder creates a new mock instance.
func NewMockAuthorizationEncoder(ctrl *gomock.Controller) *MockAuthorizationEncoder {
	mock := &MockAuthorizationEncoder{ctrl: ctrl}
	mock.recorder = &MockAuthorizationEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationEncoder) EXPECT() *MockAuthorizationEncoderMockRecorder {
	return m.recorder
}

// Encode mocks base method.
func (m *MockAuthorizationEncoder) Encode(ctx context.Context, ar *flowv1.AuthorizationRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", ctx, ar)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockAuthorizationEncoderMockRecorder) Encode(ctx, ar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockAuthorizationEncoder)(nil).Encode), ctx, ar)
}
