// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/generator (interfaces: AuthorizationCode)
//
// Generated by this command:
//
//	mockgen -destination mock/authorization_code.gen.go -package mock zntr.io/solid/sdk/generator AuthorizationCode
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationCode is a mock of AuthorizationCode interface.
type MockAuthorizationCode struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationCodeMockRecorder
	isgomock struct{}
}

// MockAuthorizationCodeMockRecorder is the mock recorder for MockAuthorizationCode.
type MockAuthorizationCodeMockRecorder struct {
	mock *MockAuthorizationCode
}

// NewMockAuthorizationCode creates a new mock instance.
func NewMockAuthorizationCode(ctrl *gomock.Controller) *MockAuthorizationCode {
	mock := &MockAuthorizationCode{ctrl: ctrl}
	mock.recorder = &MockAuthorizationCodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationCode) EXPECT() *MockAuthorizationCodeMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAuthorizationCode) Generate(ctx context.Context, issuer string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, issuer)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAuthorizationCodeMockRecorder) Generate(ctx, issuer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAuthorizationCode)(nil).Generate), ctx, issuer)
}

// Validate mocks base method.
func (m *MockAuthorizationCode) Validate(ctx context.Context, issuer, in string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, issuer, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockAuthorizationCodeMockRecorder) Validate(ctx, issuer, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockAuthorizationCode)(nil).Validate), ctx, issuer, in)
}
