// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/generator (interfaces: RequestURI)
//
// Generated by this command:
//
//	mockgen -destination mock/request_uri.gen.go -package mock zntr.io/solid/sdk/generator RequestURI
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestURI is a mock of RequestURI interface.
type MockRequestURI struct {
	ctrl     *gomock.Controller
	recorder *MockRequestURIMockRecorder
	isgomock struct{}
}

// MockRequestURIMockRecorder is the mock recorder for MockRequestURI.
type MockRequestURIMockRecorder struct {
	mock *MockRequestURI
}

// NewMockRequestURI creates a new mock instance.
func NewMockRequestURI(ctrl *gomock.Controller) *MockRequestURI {
	mock := &MockRequestURI{ctrl: ctrl}
	mock.recorder = &MockRequestURIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestURI) EXPECT() *MockRequestURIMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRequestURI) Generate(ctx context.Context, issuer string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, issuer)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockRequestURIMockRecorder) Generate(ctx, issuer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRequestURI)(nil).Generate), ctx, issuer)
}

// Validate mocks base method.
func (m *MockRequestURI) Validate(ctx context.Context, issuer, in string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, issuer, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockRequestURIMockRecorder) Validate(ctx, issuer, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockRequestURI)(nil).Validate), ctx, issuer, in)
}
