// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: BackchannelAuthenticationSession)
//
// Generated by this command:
//
//	mockgen -destination mock/backchannel_authentication_session.gen.go -package mock zntr.io/solid/server/storage BackchannelAuthenticationSession
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	sessionv1 "zntr.io/solid/api/oidc/session/v1"
)

// MockBackchannelAuthenticationSession is a mock of BackchannelAuthenticationSession interface.
type MockBackchannelAuthenticationSession struct {
	ctrl     *gomock.Controller
	recorder *MockBackchannelAuthenticationSessionMockRecorder
	isgomock struct{}
}

// MockBackchannelAuthenticationSessionMockRecorder is the mock recorder for MockBackchannelAuthenticationSession.
type MockBackchannelAuthenticationSessionMockRecorder struct {
	mock *MockBackchannelAuthenticationSession
}

// NewMockBackchannelAuthenticationSession creates a new mock instance.
func NewMockBackchannelAuthenticationSession(ctrl *gomock.Controller) *MockBackchannelAuthenticationSession {
	mock := &MockBackchannelAuthenticationSession{ctrl: ctrl}
	mock.recorder = &MockBackchannelAuthenticationSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackchannelAuthenticationSession) EXPECT() *MockBackchannelAuthenticationSessionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackchannelAuthenticationSession) Delete(ctx context.Context, issuer, authReqID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, issuer, authReqID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) Delete(ctx, issuer, authReqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).Delete), ctx, issuer, authReqID)
}

// DeleteAndGetByAuthReqID mocks base method.
func (m *MockBackchannelAuthenticationSession) DeleteAndGetByAuthReqID(ctx context.Context, issuer, authReqID string) (*sessionv1.BackchannelAuthenticationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndGetByAuthReqID", ctx, issuer, authReqID)
	ret0, _ := ret[0].(*sessionv1.BackchannelAuthenticationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAndGetByAuthReqID indicates an expected call of DeleteAndGetByAuthReqID.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) DeleteAndGetByAuthReqID(ctx, issuer, authReqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndGetByAuthReqID", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).DeleteAndGetByAuthReqID), ctx, issuer, authReqID)
}

// GetByAuthReqID mocks base method.
func (m *MockBackchannelAuthenticationSession) GetByAuthReqID(ctx context.Context, issuer, authReqID string) (*sessionv1.BackchannelAuthenticationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuthReqID", ctx, issuer, authReqID)
	ret0, _ := ret[0].(*sessionv1.BackchannelAuthenticationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAuthReqID indicates an expected call of GetByAuthReqID.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) GetByAuthReqID(ctx, issuer, authReqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuthReqID", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).GetByAuthReqID), ctx, issuer, authReqID)
}

// Register mocks base method.
func (m *MockBackchannelAuthenticationSession) Register(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) Register(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).Register), ctx, issuer, authReqID, r)
}

// UpdateByAuthReqID mocks base method.
func (m *MockBackchannelAuthenticationSession) UpdateByAuthReqID(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByAuthReqID", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByAuthReqID indicates an expected call of UpdateByAuthReqID.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) UpdateByAuthReqID(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByAuthReqID", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).UpdateByAuthReqID), ctx, issuer, authReqID, r)
}

// Validate mocks base method.
func (m *MockBackchannelAuthenticationSession) Validate(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockBackchannelAuthenticationSessionMockRecorder) Validate(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockBackchannelAuthenticationSession)(nil).Validate), ctx, issuer, authReqID, r)
}
