// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: BackchannelAuthenticationSessionWriter)
//
// Generated by this command:
//
//	mockgen -destination mock/backchannel_authentication_session_writer.gen.go -package mock zntr.io/solid/server/storage BackchannelAuthenticationSessionWriter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	sessionv1 "zntr.io/solid/api/oidc/session/v1"
)

// MockBackchannelAuthenticationSessionWriter is a mock of BackchannelAuthenticationSessionWriter interface.
type MockBackchannelAuthenticationSessionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBackchannelAuthenticationSessionWriterMockRecorder
	isgomock struct{}
}

// MockBackchannelAuthenticationSessionWriterMockRecorder is the mock recorder for MockBackchannelAuthenticationSessionWriter.
type MockBackchannelAuthenticationSessionWriterMockRecorder struct {
	mock *MockBackchannelAuthenticationSessionWriter
}

// NewMockBackchannelAuthenticationSessionWriter creates a new mock instance.
func NewMockBackchannelAuthenticationSessionWriter(ctrl *gomock.Controller) *MockBackchannelAuthenticationSessionWriter {
	mock := &MockBackchannelAuthenticationSessionWriter{ctrl: ctrl}
	mock.recorder = &MockBackchannelAuthenticationSessionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackchannelAuthenticationSessionWriter) EXPECT() *MockBackchannelAuthenticationSessionWriterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackchannelAuthenticationSessionWriter) Delete(ctx context.Context, issuer, authReqID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, issuer, authReqID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackchannelAuthenticationSessionWriterMockRecorder) Delete(ctx, issuer, authReqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackchannelAuthenticationSessionWriter)(nil).Delete), ctx, issuer, authReqID)
}

// DeleteAndGetByAuthReqID mocks base method.
func (m *MockBackchannelAuthenticationSessionWriter) DeleteAndGetByAuthReqID(ctx context.Context, issuer, authReqID string) (*sessionv1.BackchannelAuthenticationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndGetByAuthReqID", ctx, issuer, authReqID)
	ret0, _ := ret[0].(*sessionv1.BackchannelAuthenticationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAndGetByAuthReqID indicates an expected call of DeleteAndGetByAuthReqID.
func (mr *MockBackchannelAuthenticationSessionWriterMockRecorder) DeleteAndGetByAuthReqID(ctx, issuer, authReqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndGetByAuthReqID", reflect.TypeOf((*MockBackchannelAuthenticationSessionWriter)(nil).DeleteAndGetByAuthReqID), ctx, issuer, authReqID)
}

// Register mocks base method.
func (m *MockBackchannelAuthenticationSessionWriter) Register(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockBackchannelAuthenticationSessionWriterMockRecorder) Register(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBackchannelAuthenticationSessionWriter)(nil).Register), ctx, issuer, authReqID, r)
}

// UpdateByAuthReqID mocks base method.
func (m *MockBackchannelAuthenticationSessionWriter) UpdateByAuthReqID(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByAuthReqID", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByAuthReqID indicates an expected call of UpdateByAuthReqID.
func (mr *MockBackchannelAuthenticationSessionWriterMockRecorder) UpdateByAuthReqID(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByAuthReqID", reflect.TypeOf((*MockBackchannelAuthenticationSessionWriter)(nil).UpdateByAuthReqID), ctx, issuer, authReqID, r)
}

// Validate mocks base method.
func (m *MockBackchannelAuthenticationSessionWriter) Validate(ctx context.Context, issuer, authReqID string, r *sessionv1.BackchannelAuthenticationSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, issuer, authReqID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockBackchannelAuthenticationSessionWriterMockRecorder) Validate(ctx, issuer, authReqID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockBackchannelAuthenticationSessionWriter)(nil).Validate), ctx, issuer, authReqID, r)
}
