// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: ClientReader)
//
// Generated by this command:
//
//	mockgen -destination mock/clientreader.gen.go -package mock zntr.io/solid/server/storage ClientReader
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	clientv1 "zntr.io/solid/api/oidc/client/v1"
)

// MockClientReader is a mock of ClientReader interface.
type MockClientReader struct {
	ctrl     *gomock.Controller
	recorder *MockClientReaderMockRecorder
	isgomock struct{}
}

// MockClientReaderMockRecorder is the mock recorder for MockClientReader.
type MockClientReaderMockRecorder struct {
	mock *MockClientReader
}

// NewMockClientReader creates a new mock instance.
func NewMockClientReader(ctrl *gomock.Controller) *MockClientReader {
	mock := &MockClientReader{ctrl: ctrl}
	mock.recorder = &MockClientReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientReader) EXPECT() *MockClientReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClientReader) Get(ctx context.Context, id string) (*clientv1.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*clientv1.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientReaderMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientReader)(nil).Get), ctx, id)
}

// GetByName mocks base method.
func (m *MockClientReader) GetByName(ctx context.Context, name string) (*clientv1.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*clientv1.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockClientReaderMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockClientReader)(nil).GetByName), ctx, name)
}
