// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: DeviceCodeSession)
//
// Generated by this command:
//
//	mockgen -destination mock/device_code_session.gen.go -package mock zntr.io/solid/server/storage DeviceCodeSession
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	sessionv1 "zntr.io/solid/api/oidc/session/v1"
)

// MockDeviceCodeSession is a mock of DeviceCodeSession interface.
type MockDeviceCodeSession struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceCodeSessionMockRecorder
	isgomock struct{}
}

// MockDeviceCodeSessionMockRecorder is the mock recorder for MockDeviceCodeSession.
type MockDeviceCodeSessionMockRecorder struct {
	mock *MockDeviceCodeSession
}

// NewMockDeviceCodeSession creates a new mock instance.
func NewMockDeviceCodeSession(ctrl *gomock.Controller) *MockDeviceCodeSession {
	mock := &MockDeviceCodeSession{ctrl: ctrl}
	mock.recorder = &MockDeviceCodeSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceCodeSession) EXPECT() *MockDeviceCodeSessionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeviceCodeSession) Delete(ctx context.Context, issuer, userCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, issuer, userCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceCodeSessionMockRecorder) Delete(ctx, issuer, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceCodeSession)(nil).Delete), ctx, issuer, userCode)
}

// DeleteAndGetByDeviceCode mocks base method.
func (m *MockDeviceCodeSession) DeleteAndGetByDeviceCode(ctx context.Context, issuer, deviceCode string) (*sessionv1.DeviceCodeSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndGetByDeviceCode", ctx, issuer, deviceCode)
	ret0, _ := ret[0].(*sessionv1.DeviceCodeSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAndGetByDeviceCode indicates an expected call of DeleteAndGetByDeviceCode.
func (mr *MockDeviceCodeSessionMockRecorder) DeleteAndGetByDeviceCode(ctx, issuer, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndGetByDeviceCode", reflect.TypeOf((*MockDeviceCodeSession)(nil).DeleteAndGetByDeviceCode), ctx, issuer, deviceCode)
}

// GetByDeviceCode mocks base method.
func (m *MockDeviceCodeSession) GetByDeviceCode(ctx context.Context, issuer, deviceCode string) (*sessionv1.DeviceCodeSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceCode", ctx, issuer, deviceCode)
	ret0, _ := ret[0].(*sessionv1.DeviceCodeSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceCode indicates an expected call of GetByDeviceCode.
func (mr *MockDeviceCodeSessionMockRecorder) GetByDeviceCode(ctx, issuer, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceCode", reflect.TypeOf((*MockDeviceCodeSession)(nil).GetByDeviceCode), ctx, issuer, deviceCode)
}

// GetByUserCode mocks base method.
func (m *MockDeviceCodeSession) GetByUserCode(ctx context.Context, issuer, userCode string) (*sessionv1.DeviceCodeSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCode", ctx, issuer, userCode)
	ret0, _ := ret[0].(*sessionv1.DeviceCodeSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCode indicates an expected call of GetByUserCode.
func (mr *MockDeviceCodeSessionMockRecorder) GetByUserCode(ctx, issuer, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCode", reflect.TypeOf((*MockDeviceCodeSession)(nil).GetByUserCode), ctx, issuer, userCode)
}

// Register mocks base method.
func (m *MockDeviceCodeSession) Register(ctx context.Context, issuer, userCode string, r *sessionv1.DeviceCodeSession) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, issuer, userCode, r)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockDeviceCodeSessionMockRecorder) Register(ctx, issuer, userCode, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDeviceCodeSession)(nil).Register), ctx, issuer, userCode, r)
}

// UpdateByDeviceCode mocks base method.
func (m *MockDeviceCodeSession) UpdateByDeviceCode(ctx context.Context, issuer, deviceCode string, r *sessionv1.DeviceCodeSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByDeviceCode", ctx, issuer, deviceCode, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByDeviceCode indicates an expected call of UpdateByDeviceCode.
func (mr *MockDeviceCodeSessionMockRecorder) UpdateByDeviceCode(ctx, issuer, deviceCode, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByDeviceCode", reflect.TypeOf((*MockDeviceCodeSession)(nil).UpdateByDeviceCode), ctx, issuer, deviceCode, r)
}

// Validate mocks base method.
func (m *MockDeviceCodeSession) Validate(ctx context.Context, issuer, userCode string, r *sessionv1.DeviceCodeSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, issuer, userCode, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockDeviceCodeSessionMockRecorder) Validate(ctx, issuer, userCode, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockDeviceCodeSession)(nil).Validate), ctx, issuer, userCode, r)
}
