// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: DPoP)
//
// Generated by this command:
//
//	mockgen -destination mock/dpop.gen.go -package mock zntr.io/solid/server/storage DPoP
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDPoP is a mock of DPoP interface.
type MockDPoP struct {
	ctrl     *gomock.Controller
	recorder *MockDPoPMockRecorder
	isgomock struct{}
}

// MockDPoPMockRecorder is the mock recorder for MockDPoP.
type MockDPoPMockRecorder struct {
	mock *MockDPoP
}

// NewMockDPoP creates a new mock instance.
func NewMockDPoP(ctrl *gomock.Controller) *MockDPoP {
	mock := &MockDPoP{ctrl: ctrl}
	mock.recorder = &MockDPoPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDPoP) EXPECT() *MockDPoPMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDPoP) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDPoPMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDPoP)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockDPoP) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDPoPMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDPoP)(nil).Exists), ctx, id)
}

// Register mocks base method.
func (m *MockDPoP) Register(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockDPoPMockRecorder) Register(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDPoP)(nil).Register), ctx, id)
}
