// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: ResourceReader)
//
// Generated by this command:
//
//	mockgen -destination mock/resource_reader.gen.go -package mock zntr.io/solid/server/storage ResourceReader
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	resourcev1 "zntr.io/solid/api/oidc/resource/v1"
)

// MockResourceReader is a mock of ResourceReader interface.
type MockResourceReader struct {
	ctrl     *gomock.Controller
	recorder *MockResourceReaderMockRecorder
	isgomock struct{}
}

// MockResourceReaderMockRecorder is the mock recorder for MockResourceReader.
type MockResourceReaderMockRecorder struct {
	mock *MockResourceReader
}

// NewMockResourceReader creates a new mock instance.
func NewMockResourceReader(ctrl *gomock.Controller) *MockResourceReader {
	mock := &MockResourceReader{ctrl: ctrl}
	mock.recorder = &MockResourceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceReader) EXPECT() *MockResourceReaderMockRecorder {
	return m.recorder
}

// GetByURI mocks base method.
func (m *MockResourceReader) GetByURI(ctx context.Context, urn string) (*resourcev1.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURI", ctx, urn)
	ret0, _ := ret[0].(*resourcev1.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURI indicates an expected call of GetByURI.
func (mr *MockResourceReaderMockRecorder) GetByURI(ctx, urn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURI", reflect.TypeOf((*MockResourceReader)(nil).GetByURI), ctx, urn)
}
