// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/server/storage (interfaces: Token)
//
// Generated by this command:
//
//	mockgen -destination mock/token.gen.go -package mock zntr.io/solid/server/storage Token
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	tokenv1 "zntr.io/solid/api/oidc/token/v1"
)

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
	isgomock struct{}
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &MockTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockToken) Create(ctx context.Context, issuer string, t *tokenv1.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, issuer, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTokenMockRecorder) Create(ctx, issuer, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockToken)(nil).Create), ctx, issuer, t)
}

// Delete mocks base method.
func (m *MockToken) Delete(ctx context.Context, issuer, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, issuer, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenMockRecorder) Delete(ctx, issuer, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockToken)(nil).Delete), ctx, issuer, id)
}

// Get mocks base method.
func (m *MockToken) Get(ctx context.Context, issuer, id string) (*tokenv1.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, issuer, id)
	ret0, _ := ret[0].(*tokenv1.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTokenMockRecorder) Get(ctx, issuer, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockToken)(nil).Get), ctx, issuer, id)
}

// GetByGrantID mocks base method.
func (m *MockToken) GetByGrantID(ctx context.Context, issuer, grantID string) []*tokenv1.Token {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGrantID", ctx, issuer, grantID)
	ret0, _ := ret[0].([]*tokenv1.Token)
	return ret0
}

// GetByGrantID indicates an expected call of GetByGrantID.
func (mr *MockTokenMockRecorder) GetByGrantID(ctx, issuer, grantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGrantID", reflect.TypeOf((*MockToken)(nil).GetByGrantID), ctx, issuer, grantID)
}

// GetByValue mocks base method.
func (m *MockToken) GetByValue(ctx context.Context, issuer, value string) (*tokenv1.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByValue", ctx, issuer, value)
	ret0, _ := ret[0].(*tokenv1.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByValue indicates an expected call of GetByValue.
func (mr *MockTokenMockRecorder) GetByValue(ctx, issuer, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByValue", reflect.TypeOf((*MockToken)(nil).GetByValue), ctx, issuer, value)
}

// Revoke mocks base method.
func (m *MockToken) Revoke(ctx context.Context, issuer, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, issuer, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenMockRecorder) Revoke(ctx, issuer, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockToken)(nil).Revoke), ctx, issuer, id)
}
