// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/discovery/v1/resource.proto

package discoveryv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtectedResourceMetadata describes the Protected Resource Metadata properties.
// https://www.rfc-editor.org/rfc/rfc9728#name-protected-resource-metadata
type ProtectedResourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. The protected resource's resource identifier, which is a URL that
	// uses the https scheme and has no fragment components.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// OPTIONAL. JSON array containing a list of OAuth authorization server issuer
	// identifiers, as defined in [OAuth.AuthorizationMetadata], for authorization
	// servers that can be used with this protected resource. Protected resources
	// MAY choose not to advertise some supported authorization servers even when
	// this parameter is used. In some use cases, the set of authorization servers
	// will not be enumerable, in which case this metadata parameter would not be
	// used.
	AuthorizationServers []string `protobuf:"bytes,2,rep,name=authorization_servers,json=authorizationServers,proto3" json:"authorization_servers,omitempty"`
	// OPTIONAL. URL of the protected resource's JWK Set [JWK] document. This
	// contains keys belonging to the protected resource. For instance, this JWK
	// Set MAY contain encryption key(s) that are used to encrypt access tokens
	// to the protected resource. When both signing and encryption keys are made
	// available, a use (public key use) parameter value is REQUIRED for all keys
	// in the referenced JWK Set to indicate each key's intended usage.
	JwksUri *string `protobuf:"bytes,3,opt,name=jwks_uri,json=jwksUri,proto3,oneof" json:"jwks_uri,omitempty"`
	// RECOMMENDED. JSON array containing a list of the OAuth 2.0 [RFC6749] scope
	// values that are used in authorization requests to request access to this
	// protected resource. Protected resources MAY choose not to advertise some
	// scope values supported even when this parameter is used.
	ScopesSupported []string `protobuf:"bytes,4,rep,name=scopes_supported,json=scopesSupported,proto3" json:"scopes_supported,omitempty"`
	// OPTIONAL. JSON array containing a list of the OAuth 2.0 Bearer Token
	// [RFC6750] presentation methods that this protected resource supports.
	// Defined values are ["header", "fragment", "query"], corresponding to
	// Sections 2.1, 2.2, and 2.3 of RFC 6750.
	BearerMethodsSupported []string `protobuf:"bytes,5,rep,name=bearer_methods_supported,json=bearerMethodsSupported,proto3" json:"bearer_methods_supported,omitempty"`
	// OPTIONAL. JSON array containing a list of the JWS [JWS] signing algorithms
	// (alg values) [JWA] supported by the protected resource for signed content.
	// The value none MUST NOT be used.
	ResourceSigningAlgValuesSupported []string `protobuf:"bytes,6,rep,name=resource_signing_alg_values_supported,json=resourceSigningAlgValuesSupported,proto3" json:"resource_signing_alg_values_supported,omitempty"`
	// OPTIONAL. JSON array containing a list of the JWE [JWE] encryption
	// algorithms (alg values) [JWA] supported by the protected resource for
	// encrypted content.
	ResourceEncryptionAlgValuesSupported []string `protobuf:"bytes,7,rep,name=resource_encryption_alg_values_supported,json=resourceEncryptionAlgValuesSupported,proto3" json:"resource_encryption_alg_values_supported,omitempty"`
	// OPTIONAL. JSON array containing a list of the JWE encryption algorithms
	// (enc values) [JWA] supported by the protected resource for encrypted
	// content.
	ResourceEncryptionEncValuesSupported []string `protobuf:"bytes,8,rep,name=resource_encryption_enc_values_supported,json=resourceEncryptionEncValuesSupported,proto3" json:"resource_encryption_enc_values_supported,omitempty"`
	// OPTIONAL. URL of a page containing human-readable information that
	// developers might want or need to know when using the protected resource.
	ResourceDocumentation *string `protobuf:"bytes,9,opt,name=resource_documentation,json=resourceDocumentation,proto3,oneof" json:"resource_documentation,omitempty"`
	// OPTIONAL. URL that the protected resource provides to read about the
	// protected resource's requirements on how the client can use the data
	// provided by the protected resource.
	ResourcePolicyUri *string `protobuf:"bytes,10,opt,name=resource_policy_uri,json=resourcePolicyUri,proto3,oneof" json:"resource_policy_uri,omitempty"`
	// OPTIONAL. URL that the protected resource provides to read about the
	// protected resource's terms of service.
	ResourceTosUri *string `protobuf:"bytes,11,opt,name=resource_tos_uri,json=resourceTosUri,proto3,oneof" json:"resource_tos_uri,omitempty"`
	// OPTIONAL. A JWT containing metadata values about the protected resource as
	// claims. This is a string value consisting of the entire signed JWT. A
	// signed_metadata metadata value SHOULD NOT appear as a claim in the JWT.
	SignedMetadata *string `protobuf:"bytes,12,opt,name=signed_metadata,json=signedMetadata,proto3,oneof" json:"signed_metadata,omitempty"`
	// OPTIONAL. Human-readable name of the protected resource intended for
	// display to the end user.
	ResourceName *string `protobuf:"bytes,14,opt,name=resource_name,json=resourceName,proto3,oneof" json:"resource_name,omitempty"`
	// OPTIONAL. Boolean value indicating protected resource support for
	// mutual-TLS client certificate-bound access tokens [RFC8705].
	TlsClientCertificateBoundAccessTokens *bool `protobuf:"varint,15,opt,name=tls_client_certificate_bound_access_tokens,json=tlsClientCertificateBoundAccessTokens,proto3,oneof" json:"tls_client_certificate_bound_access_tokens,omitempty"`
	// OPTIONAL. JSON array containing a list of the authorization details type
	// values supported by the resource server [RFC9396].
	AuthorizationDetailsTypesSupported []string `protobuf:"bytes,16,rep,name=authorization_details_types_supported,json=authorizationDetailsTypesSupported,proto3" json:"authorization_details_types_supported,omitempty"`
	// OPTIONAL. JSON array containing a list of the JWS alg values supported by
	// the resource server for validating DPoP proof JWTs [RFC9449].
	DpopSigningAlgValuesSupported []string `protobuf:"bytes,17,rep,name=dpop_signing_alg_values_supported,json=dpopSigningAlgValuesSupported,proto3" json:"dpop_signing_alg_values_supported,omitempty"`
	// OPTIONAL. Boolean value specifying whether the protected resource always
	// requires the use of DPoP-bound access tokens [RFC9449].
	DpopBoundAccessTokensRequired *bool `protobuf:"varint,18,opt,name=dpop_bound_access_tokens_required,json=dpopBoundAccessTokensRequired,proto3,oneof" json:"dpop_bound_access_tokens_required,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ProtectedResourceMetadata) Reset() {
	*x = ProtectedResourceMetadata{}
	mi := &file_oidc_discovery_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedResourceMetadata) ProtoMessage() {}

func (x *ProtectedResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_discovery_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedResourceMetadata.ProtoReflect.Descriptor instead.
func (*ProtectedResourceMetadata) Descriptor() ([]byte, []int) {
	return file_oidc_discovery_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ProtectedResourceMetadata) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetAuthorizationServers() []string {
	if x != nil {
		return x.AuthorizationServers
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetJwksUri() string {
	if x != nil && x.JwksUri != nil {
		return *x.JwksUri
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetScopesSupported() []string {
	if x != nil {
		return x.ScopesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetBearerMethodsSupported() []string {
	if x != nil {
		return x.BearerMethodsSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetResourceSigningAlgValuesSupported() []string {
	if x != nil {
		return x.ResourceSigningAlgValuesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetResourceEncryptionAlgValuesSupported() []string {
	if x != nil {
		return x.ResourceEncryptionAlgValuesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetResourceEncryptionEncValuesSupported() []string {
	if x != nil {
		return x.ResourceEncryptionEncValuesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetResourceDocumentation() string {
	if x != nil && x.ResourceDocumentation != nil {
		return *x.ResourceDocumentation
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetResourcePolicyUri() string {
	if x != nil && x.ResourcePolicyUri != nil {
		return *x.ResourcePolicyUri
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetResourceTosUri() string {
	if x != nil && x.ResourceTosUri != nil {
		return *x.ResourceTosUri
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetSignedMetadata() string {
	if x != nil && x.SignedMetadata != nil {
		return *x.SignedMetadata
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetResourceName() string {
	if x != nil && x.ResourceName != nil {
		return *x.ResourceName
	}
	return ""
}

func (x *ProtectedResourceMetadata) GetTlsClientCertificateBoundAccessTokens() bool {
	if x != nil && x.TlsClientCertificateBoundAccessTokens != nil {
		return *x.TlsClientCertificateBoundAccessTokens
	}
	return false
}

func (x *ProtectedResourceMetadata) GetAuthorizationDetailsTypesSupported() []string {
	if x != nil {
		return x.AuthorizationDetailsTypesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetDpopSigningAlgValuesSupported() []string {
	if x != nil {
		return x.DpopSigningAlgValuesSupported
	}
	return nil
}

func (x *ProtectedResourceMetadata) GetDpopBoundAccessTokensRequired() bool {
	if x != nil && x.DpopBoundAccessTokensRequired != nil {
		return *x.DpopBoundAccessTokensRequired
	}
	return false
}

var File_oidc_discovery_v1_resource_proto protoreflect.FileDescriptor

const file_oidc_discovery_v1_resource_proto_rawDesc = "" +
	"\n" +
	" oidc/discovery/v1/resource.proto\x12\x11oidc.discovery.v1\x1a\x1bbuf/validate/validate.proto\"\xc1\n" +
	"\n" +
	"\x19ProtectedResourceMetadata\x12)\n" +
	"\bresource\x18\x01 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x01\x18\x80\x10\x88\x01\x01R\bresource\x123\n" +
	"\x15authorization_servers\x18\x02 \x03(\tR\x14authorizationServers\x12+\n" +
	"\bjwks_uri\x18\x03 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01H\x00R\ajwksUri\x88\x01\x01\x12)\n" +
	"\x10scopes_supported\x18\x04 \x03(\tR\x0fscopesSupported\x128\n" +
	"\x18bearer_methods_supported\x18\x05 \x03(\tR\x16bearerMethodsSupported\x12P\n" +
	"%resource_signing_alg_values_supported\x18\x06 \x03(\tR!resourceSigningAlgValuesSupported\x12V\n" +
	"(resource_encryption_alg_values_supported\x18\a \x03(\tR$resourceEncryptionAlgValuesSupported\x12V\n" +
	"(resource_encryption_enc_values_supported\x18\b \x03(\tR$resourceEncryptionEncValuesSupported\x12D\n" +
	"\x16resource_documentation\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x01R\x15resourceDocumentation\x88\x01\x01\x12=\n" +
	"\x13resource_policy_uri\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x02R\x11resourcePolicyUri\x88\x01\x01\x127\n" +
	"\x10resource_tos_uri\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x03R\x0eresourceTosUri\x88\x01\x01\x12,\n" +
	"\x0fsigned_metadata\x18\f \x01(\tH\x04R\x0esignedMetadata\x88\x01\x01\x12(\n" +
	"\rresource_name\x18\x0e \x01(\tH\x05R\fresourceName\x88\x01\x01\x12^\n" +
	"*tls_client_certificate_bound_access_tokens\x18\x0f \x01(\bH\x06R%tlsClientCertificateBoundAccessTokens\x88\x01\x01\x12Q\n" +
	"%authorization_details_types_supported\x18\x10 \x03(\tR\"authorizationDetailsTypesSupported\x12H\n" +
	"!dpop_signing_alg_values_supported\x18\x11 \x03(\tR\x1ddpopSigningAlgValuesSupported\x12M\n" +
	"!dpop_bound_access_tokens_required\x18\x12 \x01(\bH\aR\x1ddpopBoundAccessTokensRequired\x88\x01\x01B\v\n" +
	"\t_jwks_uriB\x19\n" +
	"\x17_resource_documentationB\x16\n" +
	"\x14_resource_policy_uriB\x13\n" +
	"\x11_resource_tos_uriB\x12\n" +
	"\x10_signed_metadataB\x10\n" +
	"\x0e_resource_nameB-\n" +
	"+_tls_client_certificate_bound_access_tokensB$\n" +
	"\"_dpop_bound_access_tokens_requiredB1Z/zntr.io/solid/api/oidc/discovery/v1;discoveryv1b\x06proto3"

var (
	file_oidc_discovery_v1_resource_proto_rawDescOnce sync.Once
	file_oidc_discovery_v1_resource_proto_rawDescData []byte
)

func file_oidc_discovery_v1_resource_proto_rawDescGZIP() []byte {
	file_oidc_discovery_v1_resource_proto_rawDescOnce.Do(func() {
		file_oidc_discovery_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_discovery_v1_resource_proto_rawDesc), len(file_oidc_discovery_v1_resource_proto_rawDesc)))
	})
	return file_oidc_discovery_v1_resource_proto_rawDescData
}

var file_oidc_discovery_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oidc_discovery_v1_resource_proto_goTypes = []any{
	(*ProtectedResourceMetadata)(nil), // 0: oidc.discovery.v1.ProtectedResourceMetadata
}
var file_oidc_discovery_v1_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oidc_discovery_v1_resource_proto_init() }
func file_oidc_discovery_v1_resource_proto_init() {
	if File_oidc_discovery_v1_resource_proto != nil {
		return
	}
	file_oidc_discovery_v1_resource_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_discovery_v1_resource_proto_rawDesc), len(file_oidc_discovery_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_discovery_v1_resource_proto_goTypes,
		DependencyIndexes: file_oidc_discovery_v1_resource_proto_depIdxs,
		MessageInfos:      file_oidc_discovery_v1_resource_proto_msgTypes,
	}.Build()
	File_oidc_discovery_v1_resource_proto = out.File
	file_oidc_discovery_v1_resource_proto_goTypes = nil
	file_oidc_discovery_v1_resource_proto_depIdxs = nil
}
