// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/dpop (interfaces: ProofStore)
//
// Generated by this command:
//
//	mockgen -destination sdk/dpop/mock/proof_store.gen.go -package mock zntr.io/solid/sdk/dpop ProofStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProofStore is a mock of ProofStore interface.
type MockProofStore struct {
	ctrl     *gomock.Controller
	recorder *MockProofStoreMockRecorder
	isgomock struct{}
}

// MockProofStoreMockRecorder is the mock recorder for MockProofStore.
type MockProofStoreMockRecorder struct {
	mock *MockProofStore
}

// NewMockProofStore creates a new mock instance.
func NewMockProofStore(ctrl *gomock.Controller) *MockProofStore {
	mock := &MockProofStore{ctrl: ctrl}
	mock.recorder = &MockProofStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProofStore) EXPECT() *MockProofStoreMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockProofStore) Exists(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockProofStoreMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockProofStore)(nil).Exists), ctx, id)
}

// Register mocks base method.
func (m *MockProofStore) Register(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockProofStoreMockRecorder) Register(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockProofStore)(nil).Register), ctx, id)
}
