// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/dpop (interfaces: Prover)
//
// Generated by this command:
//
//	mockgen -destination sdk/dpop/mock/prover.gen.go -package mock zntr.io/solid/sdk/dpop Prover
//

// Package mock is a generated GoMock package.
package mock

import (
	gomock "go.uber.org/mock/gomock"
	reflect "reflect"

	dpop "zntr.io/solid/sdk/dpop"
)

// MockProver is a mock of Prover interface.
type MockProver struct {
	ctrl     *gomock.Controller
	recorder *MockProverMockRecorder
	isgomock struct{}
}

// MockProverMockRecorder is the mock recorder for MockProver.
type MockProverMockRecorder struct {
	mock *MockProver
}

// NewMockProver creates a new mock instance.
func NewMockProver(ctrl *gomock.Controller) *MockProver {
	mock := &MockProver{ctrl: ctrl}
	mock.recorder = &MockProverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProver) EXPECT() *MockProverMockRecorder {
	return m.recorder
}

// Prove mocks base method.
func (m *MockProver) Prove(htm, htu string, opts ...dpop.Option) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{htm, htu}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Prove", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prove indicates an expected call of Prove.
func (mr *MockProverMockRecorder) Prove(htm, htu any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{htm, htu}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prove", reflect.TypeOf((*MockProver)(nil).Prove), varargs...)
}
