// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/token/v1/authorization_detail.proto

package tokenv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One entry of the authorization_details JSON array.
// https://www.rfc-editor.org/rfc/rfc9396#section-2
type AuthorizationDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Identifier of the authorization details type. The value is
	// unique for the described API in the context of the AS.
	// https://www.rfc-editor.org/rfc/rfc9396#section-2.1
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// OPTIONAL. Array of strings representing the location of the resource
	// or RS, as absolute URIs, at which the requested action is performed.
	Locations []string `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	// OPTIONAL. Array of strings representing the kinds of actions to be
	// taken at the resource.
	Actions []string `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// OPTIONAL. Array of strings representing the kinds of data being
	// requested to be read or written.
	Datatypes []string `protobuf:"bytes,4,rep,name=datatypes,proto3" json:"datatypes,omitempty"`
	// OPTIONAL. String identifier indicating a specific resource available
	// at the API.
	Identifier *string `protobuf:"bytes,5,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`
	// OPTIONAL. Array of strings representing the types or levels of
	// privileges being requested.
	Privileges []string `protobuf:"bytes,6,rep,name=privileges,proto3" json:"privileges,omitempty"`
	// OPTIONAL. Type-specific extension fields (e.g. instructedAmount). The
	// AS validator for the type decides their validity.
	// https://www.rfc-editor.org/rfc/rfc9396#section-2.2
	Extensions    map[string]*structpb.Value `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationDetail) Reset() {
	*x = AuthorizationDetail{}
	mi := &file_oidc_token_v1_authorization_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationDetail) ProtoMessage() {}

func (x *AuthorizationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_token_v1_authorization_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationDetail.ProtoReflect.Descriptor instead.
func (*AuthorizationDetail) Descriptor() ([]byte, []int) {
	return file_oidc_token_v1_authorization_detail_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthorizationDetail) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *AuthorizationDetail) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AuthorizationDetail) GetDatatypes() []string {
	if x != nil {
		return x.Datatypes
	}
	return nil
}

func (x *AuthorizationDetail) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *AuthorizationDetail) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *AuthorizationDetail) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_oidc_token_v1_authorization_detail_proto protoreflect.FileDescriptor

const file_oidc_token_v1_authorization_detail_proto_rawDesc = "" +
	"\n" +
	"(oidc/token/v1/authorization_detail.proto\x12\roidc.token.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe2\x03\n" +
	"\x13AuthorizationDetail\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x04R\x04type\x12/\n" +
	"\tlocations\x18\x02 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10 \"\ar\x05\x10\x01\x18\x80\x10R\tlocations\x12+\n" +
	"\aactions\x18\x03 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10@\"\ar\x05\x10\x01\x18\x80\x04R\aactions\x12/\n" +
	"\tdatatypes\x18\x04 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10@\"\ar\x05\x10\x01\x18\x80\x04R\tdatatypes\x12/\n" +
	"\n" +
	"identifier\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x04H\x00R\n" +
	"identifier\x88\x01\x01\x121\n" +
	"\n" +
	"privileges\x18\x06 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10@\"\ar\x05\x10\x01\x18\x80\x04R\n" +
	"privileges\x12R\n" +
	"\n" +
	"extensions\x18\a \x03(\v22.oidc.token.v1.AuthorizationDetail.ExtensionsEntryR\n" +
	"extensions\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\r\n" +
	"\v_identifierB)Z'zntr.io/solid/api/oidc/token/v1;tokenv1b\x06proto3"

var (
	file_oidc_token_v1_authorization_detail_proto_rawDescOnce sync.Once
	file_oidc_token_v1_authorization_detail_proto_rawDescData []byte
)

func file_oidc_token_v1_authorization_detail_proto_rawDescGZIP() []byte {
	file_oidc_token_v1_authorization_detail_proto_rawDescOnce.Do(func() {
		file_oidc_token_v1_authorization_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_token_v1_authorization_detail_proto_rawDesc), len(file_oidc_token_v1_authorization_detail_proto_rawDesc)))
	})
	return file_oidc_token_v1_authorization_detail_proto_rawDescData
}

var file_oidc_token_v1_authorization_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oidc_token_v1_authorization_detail_proto_goTypes = []any{
	(*AuthorizationDetail)(nil), // 0: oidc.token.v1.AuthorizationDetail
	nil,                         // 1: oidc.token.v1.AuthorizationDetail.ExtensionsEntry
	(*structpb.Value)(nil),      // 2: google.protobuf.Value
}
var file_oidc_token_v1_authorization_detail_proto_depIdxs = []int32{
	1, // 0: oidc.token.v1.AuthorizationDetail.extensions:type_name -> oidc.token.v1.AuthorizationDetail.ExtensionsEntry
	2, // 1: oidc.token.v1.AuthorizationDetail.ExtensionsEntry.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oidc_token_v1_authorization_detail_proto_init() }
func file_oidc_token_v1_authorization_detail_proto_init() {
	if File_oidc_token_v1_authorization_detail_proto != nil {
		return
	}
	file_oidc_token_v1_authorization_detail_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_token_v1_authorization_detail_proto_rawDesc), len(file_oidc_token_v1_authorization_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_token_v1_authorization_detail_proto_goTypes,
		DependencyIndexes: file_oidc_token_v1_authorization_detail_proto_depIdxs,
		MessageInfos:      file_oidc_token_v1_authorization_detail_proto_msgTypes,
	}.Build()
	File_oidc_token_v1_authorization_detail_proto = out.File
	file_oidc_token_v1_authorization_detail_proto_goTypes = nil
	file_oidc_token_v1_authorization_detail_proto_depIdxs = nil
}
