// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/token/v1/introspection_api.proto

package tokenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "zntr.io/solid/api/oidc/client/v1"
	v11 "zntr.io/solid/api/oidc/core/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://tools.ietf.org/html/rfc7662#section-2.1
type IntrospectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Token issuer URL.
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// REQUIRED. Client that invoke the token introspection.
	Client *v1.Client `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// REQUIRED.  The string value of the token.  For access tokens, this
	// is the "access_token" value returned from the token endpoint
	// defined in OAuth 2.0 [RFC6749], Section 5.1.  For refresh tokens,
	// this is the "refresh_token" value returned from the token endpoint
	// as defined in OAuth 2.0 [RFC6749], Section 5.1.  Other token types
	// are outside the scope of this specification.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// OPTIONAL.  A hint about the type of the token submitted for
	// introspection.  The protected resource MAY pass this parameter to
	// help the authorization server optimize the token lookup.  If the
	// server is unable to locate the token using the given hint, it MUST
	// extend its search across all of its supported token types.  An
	// authorization server MAY ignore this parameter, particularly if it
	// is able to detect the token type automatically.  Values for this
	// field are defined in the "OAuth Token Type Hints" registry defined
	// in OAuth Token Revocation [RFC7009]
	TokenTypeHint *string `protobuf:"bytes,4,opt,name=token_type_hint,json=tokenTypeHint,proto3,oneof" json:"token_type_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_oidc_token_v1_introspection_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_token_v1_introspection_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_oidc_token_v1_introspection_api_proto_rawDescGZIP(), []int{0}
}

func (x *IntrospectRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IntrospectRequest) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IntrospectRequest) GetTokenTypeHint() string {
	if x != nil && x.TokenTypeHint != nil {
		return *x.TokenTypeHint
	}
	return ""
}

// https://tools.ietf.org/html/rfc7662#section-2.2
type IntrospectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *v11.Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// OPTIONAL. The matching token instance.
	Token         *Token `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_oidc_token_v1_introspection_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_token_v1_introspection_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_oidc_token_v1_introspection_api_proto_rawDescGZIP(), []int{1}
}

func (x *IntrospectResponse) GetError() *v11.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *IntrospectResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_oidc_token_v1_introspection_api_proto protoreflect.FileDescriptor

const file_oidc_token_v1_introspection_api_proto_rawDesc = "" +
	"\n" +
	"%oidc/token/v1/introspection_api.proto\x12\roidc.token.v1\x1a\x1boidc/client/v1/client.proto\x1a\x18oidc/core/v1/error.proto\x1a\x19oidc/token/v1/token.proto\"\xb2\x01\n" +
	"\x11IntrospectRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12.\n" +
	"\x06client\x18\x02 \x01(\v2\x16.oidc.client.v1.ClientR\x06client\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12+\n" +
	"\x0ftoken_type_hint\x18\x04 \x01(\tH\x00R\rtokenTypeHint\x88\x01\x01B\x12\n" +
	"\x10_token_type_hint\"k\n" +
	"\x12IntrospectResponse\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.oidc.core.v1.ErrorR\x05error\x12*\n" +
	"\x05token\x18\x02 \x01(\v2\x14.oidc.token.v1.TokenR\x05token2k\n" +
	"\x14IntrospectionService\x12S\n" +
	"\n" +
	"Introspect\x12 .oidc.token.v1.IntrospectRequest\x1a!.oidc.token.v1.IntrospectResponse\"\x00B)Z'zntr.io/solid/api/oidc/token/v1;tokenv1b\x06proto3"

var (
	file_oidc_token_v1_introspection_api_proto_rawDescOnce sync.Once
	file_oidc_token_v1_introspection_api_proto_rawDescData []byte
)

func file_oidc_token_v1_introspection_api_proto_rawDescGZIP() []byte {
	file_oidc_token_v1_introspection_api_proto_rawDescOnce.Do(func() {
		file_oidc_token_v1_introspection_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_token_v1_introspection_api_proto_rawDesc), len(file_oidc_token_v1_introspection_api_proto_rawDesc)))
	})
	return file_oidc_token_v1_introspection_api_proto_rawDescData
}

var file_oidc_token_v1_introspection_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oidc_token_v1_introspection_api_proto_goTypes = []any{
	(*IntrospectRequest)(nil),  // 0: oidc.token.v1.IntrospectRequest
	(*IntrospectResponse)(nil), // 1: oidc.token.v1.IntrospectResponse
	(*v1.Client)(nil),          // 2: oidc.client.v1.Client
	(*v11.Error)(nil),          // 3: oidc.core.v1.Error
	(*Token)(nil),              // 4: oidc.token.v1.Token
}
var file_oidc_token_v1_introspection_api_proto_depIdxs = []int32{
	2, // 0: oidc.token.v1.IntrospectRequest.client:type_name -> oidc.client.v1.Client
	3, // 1: oidc.token.v1.IntrospectResponse.error:type_name -> oidc.core.v1.Error
	4, // 2: oidc.token.v1.IntrospectResponse.token:type_name -> oidc.token.v1.Token
	0, // 3: oidc.token.v1.IntrospectionService.Introspect:input_type -> oidc.token.v1.IntrospectRequest
	1, // 4: oidc.token.v1.IntrospectionService.Introspect:output_type -> oidc.token.v1.IntrospectResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_oidc_token_v1_introspection_api_proto_init() }
func file_oidc_token_v1_introspection_api_proto_init() {
	if File_oidc_token_v1_introspection_api_proto != nil {
		return
	}
	file_oidc_token_v1_token_proto_init()
	file_oidc_token_v1_introspection_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_token_v1_introspection_api_proto_rawDesc), len(file_oidc_token_v1_introspection_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oidc_token_v1_introspection_api_proto_goTypes,
		DependencyIndexes: file_oidc_token_v1_introspection_api_proto_depIdxs,
		MessageInfos:      file_oidc_token_v1_introspection_api_proto_msgTypes,
	}.Build()
	File_oidc_token_v1_introspection_api_proto = out.File
	file_oidc_token_v1_introspection_api_proto_goTypes = nil
	file_oidc_token_v1_introspection_api_proto_depIdxs = nil
}
