// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/token/v1/revocation_api.proto

package tokenv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	v1 "zntr.io/solid/api/oidc/client/v1"
	v11 "zntr.io/solid/api/oidc/core/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://tools.ietf.org/html/rfc7009#section-2.1
type RevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Token issuer URL.
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// REQUIRED. Client that invoke the token revocation.
	Client *v1.Client `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// REQUIRED.  The token that the client wants to get revoked.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// OPTIONAL.  A hint about the type of the token
	// submitted for revocation.  Clients MAY pass this parameter in
	// order to help the authorization server to optimize the token
	// lookup.  If the server is unable to locate the token using
	// the given hint, it MUST extend its search across all of its
	// supported token types.  An authorization server MAY ignore
	// this parameter, particularly if it is able to detect the
	// token type automatically.  This specification defines two
	// such values:
	TokenTypeHint *string `protobuf:"bytes,4,opt,name=token_type_hint,json=tokenTypeHint,proto3,oneof" json:"token_type_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_oidc_token_v1_revocation_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_token_v1_revocation_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_oidc_token_v1_revocation_api_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *RevokeRequest) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RevokeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RevokeRequest) GetTokenTypeHint() string {
	if x != nil && x.TokenTypeHint != nil {
		return *x.TokenTypeHint
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *v11.Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_oidc_token_v1_revocation_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_token_v1_revocation_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_oidc_token_v1_revocation_api_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeResponse) GetError() *v11.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_oidc_token_v1_revocation_api_proto protoreflect.FileDescriptor

const file_oidc_token_v1_revocation_api_proto_rawDesc = "" +
	"\n" +
	"\"oidc/token/v1/revocation_api.proto\x12\roidc.token.v1\x1a\x1boidc/client/v1/client.proto\x1a\x18oidc/core/v1/error.proto\"\xae\x01\n" +
	"\rRevokeRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12.\n" +
	"\x06client\x18\x02 \x01(\v2\x16.oidc.client.v1.ClientR\x06client\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12+\n" +
	"\x0ftoken_type_hint\x18\x04 \x01(\tH\x00R\rtokenTypeHint\x88\x01\x01B\x12\n" +
	"\x10_token_type_hint\";\n" +
	"\x0eRevokeResponse\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.oidc.core.v1.ErrorR\x05error2[\n" +
	"\x10RevocatonService\x12G\n" +
	"\x06Revoke\x12\x1c.oidc.token.v1.RevokeRequest\x1a\x1d.oidc.token.v1.RevokeResponse\"\x00B)Z'zntr.io/solid/api/oidc/token/v1;tokenv1b\x06proto3"

var (
	file_oidc_token_v1_revocation_api_proto_rawDescOnce sync.Once
	file_oidc_token_v1_revocation_api_proto_rawDescData []byte
)

func file_oidc_token_v1_revocation_api_proto_rawDescGZIP() []byte {
	file_oidc_token_v1_revocation_api_proto_rawDescOnce.Do(func() {
		file_oidc_token_v1_revocation_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_token_v1_revocation_api_proto_rawDesc), len(file_oidc_token_v1_revocation_api_proto_rawDesc)))
	})
	return file_oidc_token_v1_revocation_api_proto_rawDescData
}

var file_oidc_token_v1_revocation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oidc_token_v1_revocation_api_proto_goTypes = []any{
	(*RevokeRequest)(nil),  // 0: oidc.token.v1.RevokeRequest
	(*RevokeResponse)(nil), // 1: oidc.token.v1.RevokeResponse
	(*v1.Client)(nil),      // 2: oidc.client.v1.Client
	(*v11.Error)(nil),      // 3: oidc.core.v1.Error
}
var file_oidc_token_v1_revocation_api_proto_depIdxs = []int32{
	2, // 0: oidc.token.v1.RevokeRequest.client:type_name -> oidc.client.v1.Client
	3, // 1: oidc.token.v1.RevokeResponse.error:type_name -> oidc.core.v1.Error
	0, // 2: oidc.token.v1.RevocatonService.Revoke:input_type -> oidc.token.v1.RevokeRequest
	1, // 3: oidc.token.v1.RevocatonService.Revoke:output_type -> oidc.token.v1.RevokeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oidc_token_v1_revocation_api_proto_init() }
func file_oidc_token_v1_revocation_api_proto_init() {
	if File_oidc_token_v1_revocation_api_proto != nil {
		return
	}
	file_oidc_token_v1_revocation_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_token_v1_revocation_api_proto_rawDesc), len(file_oidc_token_v1_revocation_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oidc_token_v1_revocation_api_proto_goTypes,
		DependencyIndexes: file_oidc_token_v1_revocation_api_proto_depIdxs,
		MessageInfos:      file_oidc_token_v1_revocation_api_proto_msgTypes,
	}.Build()
	File_oidc_token_v1_revocation_api_proto = out.File
	file_oidc_token_v1_revocation_api_proto_goTypes = nil
	file_oidc_token_v1_revocation_api_proto_depIdxs = nil
}
