// Licensed to SolID under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. SolID licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oidc/session/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "zntr.io/solid/api/oidc/client/v1"
	v11 "zntr.io/solid/api/oidc/flow/v1"
	v12 "zntr.io/solid/api/oidc/token/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationCodeStatus int32

const (
	AuthorizationCodeStatus_AUTHORIZATION_CODE_STATUS_UNSPECIFIED AuthorizationCodeStatus = 0
	AuthorizationCodeStatus_AUTHORIZATION_CODE_STATUS_ACTIVE      AuthorizationCodeStatus = 1
	AuthorizationCodeStatus_AUTHORIZATION_CODE_STATUS_CONSUMED    AuthorizationCodeStatus = 2
)

// Enum value maps for AuthorizationCodeStatus.
var (
	AuthorizationCodeStatus_name = map[int32]string{
		0: "AUTHORIZATION_CODE_STATUS_UNSPECIFIED",
		1: "AUTHORIZATION_CODE_STATUS_ACTIVE",
		2: "AUTHORIZATION_CODE_STATUS_CONSUMED",
	}
	AuthorizationCodeStatus_value = map[string]int32{
		"AUTHORIZATION_CODE_STATUS_UNSPECIFIED": 0,
		"AUTHORIZATION_CODE_STATUS_ACTIVE":      1,
		"AUTHORIZATION_CODE_STATUS_CONSUMED":    2,
	}
)

func (x AuthorizationCodeStatus) Enum() *AuthorizationCodeStatus {
	p := new(AuthorizationCodeStatus)
	*p = x
	return p
}

func (x AuthorizationCodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationCodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oidc_session_v1_session_proto_enumTypes[0].Descriptor()
}

func (AuthorizationCodeStatus) Type() protoreflect.EnumType {
	return &file_oidc_session_v1_session_proto_enumTypes[0]
}

func (x AuthorizationCodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationCodeStatus.Descriptor instead.
func (AuthorizationCodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_oidc_session_v1_session_proto_rawDescGZIP(), []int{0}
}

type DeviceCodeStatus int32

const (
	DeviceCodeStatus_DEVICE_CODE_STATUS_UNSPECIFIED           DeviceCodeStatus = 0
	DeviceCodeStatus_DEVICE_CODE_STATUS_UNKNOWN               DeviceCodeStatus = 1
	DeviceCodeStatus_DEVICE_CODE_STATUS_AUTHORIZATION_PENDING DeviceCodeStatus = 2
	DeviceCodeStatus_DEVICE_CODE_STATUS_CONFIRMATION_PENDING  DeviceCodeStatus = 3
	DeviceCodeStatus_DEVICE_CODE_STATUS_VALIDATED             DeviceCodeStatus = 4
	// Terminal state set when the end user (or the AS on its behalf)
	// refuses the device authorization request (RFC 8628 section 3.5:
	// access_denied).
	DeviceCodeStatus_DEVICE_CODE_STATUS_DENIED DeviceCodeStatus = 5
)

// Enum value maps for DeviceCodeStatus.
var (
	DeviceCodeStatus_name = map[int32]string{
		0: "DEVICE_CODE_STATUS_UNSPECIFIED",
		1: "DEVICE_CODE_STATUS_UNKNOWN",
		2: "DEVICE_CODE_STATUS_AUTHORIZATION_PENDING",
		3: "DEVICE_CODE_STATUS_CONFIRMATION_PENDING",
		4: "DEVICE_CODE_STATUS_VALIDATED",
		5: "DEVICE_CODE_STATUS_DENIED",
	}
	DeviceCodeStatus_value = map[string]int32{
		"DEVICE_CODE_STATUS_UNSPECIFIED":           0,
		"DEVICE_CODE_STATUS_UNKNOWN":               1,
		"DEVICE_CODE_STATUS_AUTHORIZATION_PENDING": 2,
		"DEVICE_CODE_STATUS_CONFIRMATION_PENDING":  3,
		"DEVICE_CODE_STATUS_VALIDATED":             4,
		"DEVICE_CODE_STATUS_DENIED":                5,
	}
)

func (x DeviceCodeStatus) Enum() *DeviceCodeStatus {
	p := new(DeviceCodeStatus)
	*p = x
	return p
}

func (x DeviceCodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oidc_session_v1_session_proto_enumTypes[1].Descriptor()
}

func (DeviceCodeStatus) Type() protoreflect.EnumType {
	return &file_oidc_session_v1_session_proto_enumTypes[1]
}

func (x DeviceCodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCodeStatus.Descriptor instead.
func (DeviceCodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_oidc_session_v1_session_proto_rawDescGZIP(), []int{1}
}

type AuthorizationCodeSession struct {
	state   protoimpl.MessageState    `protogen:"open.v1"`
	Client  *v1.Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Issuer  string                    `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject string                    `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Request *v11.AuthorizationRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	// Grant identifier minted at code issuance; used to revoke tokens on code replay.
	GrantId string `protobuf:"bytes,5,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	// Lifecycle status of the code; transitions are governed by the
	// sdk/session state machine (ACTIVE -> CONSUMED, terminal).
	Status AuthorizationCodeStatus `protobuf:"varint,6,opt,name=status,proto3,enum=oidc.session.v1.AuthorizationCodeStatus" json:"status,omitempty"`
	// OPTIONAL. DPoP key confirmation (jkt) bound to the code at
	// authorization time. When set, the token request presenting this code
	// MUST prove possession of the same key (RFC 9449 section 10
	// authorization code binding).
	Confirmation  *v12.TokenConfirmation `protobuf:"bytes,7,opt,name=confirmation,proto3,oneof" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationCodeSession) Reset() {
	*x = AuthorizationCodeSession{}
	mi := &file_oidc_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCodeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCodeSession) ProtoMessage() {}

func (x *AuthorizationCodeSession) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCodeSession.ProtoReflect.Descriptor instead.
func (*AuthorizationCodeSession) Descriptor() ([]byte, []int) {
	return file_oidc_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationCodeSession) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AuthorizationCodeSession) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthorizationCodeSession) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizationCodeSession) GetRequest() *v11.AuthorizationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthorizationCodeSession) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *AuthorizationCodeSession) GetStatus() AuthorizationCodeStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationCodeStatus_AUTHORIZATION_CODE_STATUS_UNSPECIFIED
}

func (x *AuthorizationCodeSession) GetConfirmation() *v12.TokenConfirmation {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

type DeviceCodeSession struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	Client           *v1.Client                      `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Issuer           string                          `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	ExpiresAt        uint64                          `protobuf:"fixed64,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Request          *v11.DeviceAuthorizationRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Status           DeviceCodeStatus                `protobuf:"varint,5,opt,name=status,proto3,enum=oidc.session.v1.DeviceCodeStatus" json:"status,omitempty"`
	DeviceCode       string                          `protobuf:"bytes,6,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	ConfirmationCode string                          `protobuf:"bytes,7,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	Subject          *string                         `protobuf:"bytes,8,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Scope            *string                         `protobuf:"bytes,9,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	Audience         *string                         `protobuf:"bytes,10,opt,name=audience,proto3,oneof" json:"audience,omitempty"`
	// Epoch seconds of the last token-endpoint poll; used to enforce the
	// advertised polling interval (RFC 8628 section 3.5 slow_down, RFC 10027
	// section 6.1.11 rate limiting).
	LastPolledAt uint64 `protobuf:"fixed64,11,opt,name=last_polled_at,json=lastPolledAt,proto3" json:"last_polled_at,omitempty"`
	// Required polling interval in seconds; increased by 5 seconds on every
	// slow_down (RFC 8628 section 3.5).
	PollInterval uint64 `protobuf:"fixed64,12,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	// OPTIONAL. The authorization details consented at device authorization
	// time (RFC 9396 section 3). Fixed for the tokens minted from this
	// session: the device grant has no token-endpoint narrowing.
	AuthorizationDetails []*v12.AuthorizationDetail `protobuf:"bytes,13,rep,name=authorization_details,json=authorizationDetails,proto3" json:"authorization_details,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeviceCodeSession) Reset() {
	*x = DeviceCodeSession{}
	mi := &file_oidc_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeSession) ProtoMessage() {}

func (x *DeviceCodeSession) ProtoReflect() protoreflect.Message {
	mi := &file_oidc_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeSession.ProtoReflect.Descriptor instead.
func (*DeviceCodeSession) Descriptor() ([]byte, []int) {
	return file_oidc_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceCodeSession) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceCodeSession) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *DeviceCodeSession) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *DeviceCodeSession) GetRequest() *v11.DeviceAuthorizationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DeviceCodeSession) GetStatus() DeviceCodeStatus {
	if x != nil {
		return x.Status
	}
	return DeviceCodeStatus_DEVICE_CODE_STATUS_UNSPECIFIED
}

func (x *DeviceCodeSession) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *DeviceCodeSession) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *DeviceCodeSession) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *DeviceCodeSession) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *DeviceCodeSession) GetAudience() string {
	if x != nil && x.Audience != nil {
		return *x.Audience
	}
	return ""
}

func (x *DeviceCodeSession) GetLastPolledAt() uint64 {
	if x != nil {
		return x.LastPolledAt
	}
	return 0
}

func (x *DeviceCodeSession) GetPollInterval() uint64 {
	if x != nil {
		return x.PollInterval
	}
	return 0
}

func (x *DeviceCodeSession) GetAuthorizationDetails() []*v12.AuthorizationDetail {
	if x != nil {
		return x.AuthorizationDetails
	}
	return nil
}

var File_oidc_session_v1_session_proto protoreflect.FileDescriptor

const file_oidc_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1doidc/session/v1/session.proto\x12\x0foidc.session.v1\x1a\x1boidc/client/v1/client.proto\x1a\x17oidc/flow/v1/flow.proto\x1a\x1boidc/flow/v1/flow_api.proto\x1a(oidc/token/v1/authorization_detail.proto\x1a\x19oidc/token/v1/token.proto\"\xf3\x02\n" +
	"\x18AuthorizationCodeSession\x12.\n" +
	"\x06client\x18\x01 \x01(\v2\x16.oidc.client.v1.ClientR\x06client\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12<\n" +
	"\arequest\x18\x04 \x01(\v2\".oidc.flow.v1.AuthorizationRequestR\arequest\x12\x19\n" +
	"\bgrant_id\x18\x05 \x01(\tR\agrantId\x12@\n" +
	"\x06status\x18\x06 \x01(\x0e2(.oidc.session.v1.AuthorizationCodeStatusR\x06status\x12I\n" +
	"\fconfirmation\x18\a \x01(\v2 .oidc.token.v1.TokenConfirmationH\x00R\fconfirmation\x88\x01\x01B\x0f\n" +
	"\r_confirmation\"\xe9\x04\n" +
	"\x11DeviceCodeSession\x12.\n" +
	"\x06client\x18\x01 \x01(\v2\x16.oidc.client.v1.ClientR\x06client\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x06R\texpiresAt\x12B\n" +
	"\arequest\x18\x04 \x01(\v2(.oidc.flow.v1.DeviceAuthorizationRequestR\arequest\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.oidc.session.v1.DeviceCodeStatusR\x06status\x12\x1f\n" +
	"\vdevice_code\x18\x06 \x01(\tR\n" +
	"deviceCode\x12+\n" +
	"\x11confirmation_code\x18\a \x01(\tR\x10confirmationCode\x12\x1d\n" +
	"\asubject\x18\b \x01(\tH\x00R\asubject\x88\x01\x01\x12\x19\n" +
	"\x05scope\x18\t \x01(\tH\x01R\x05scope\x88\x01\x01\x12\x1f\n" +
	"\baudience\x18\n" +
	" \x01(\tH\x02R\baudience\x88\x01\x01\x12$\n" +
	"\x0elast_polled_at\x18\v \x01(\x06R\flastPolledAt\x12#\n" +
	"\rpoll_interval\x18\f \x01(\x06R\fpollInterval\x12W\n" +
	"\x15authorization_details\x18\r \x03(\v2\".oidc.token.v1.AuthorizationDetailR\x14authorizationDetailsB\n" +
	"\n" +
	"\b_subjectB\b\n" +
	"\x06_scopeB\v\n" +
	"\t_audience*\x92\x01\n" +
	"\x17AuthorizationCodeStatus\x12)\n" +
	"%AUTHORIZATION_CODE_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" AUTHORIZATION_CODE_STATUS_ACTIVE\x10\x01\x12&\n" +
	"\"AUTHORIZATION_CODE_STATUS_CONSUMED\x10\x02*\xf2\x01\n" +
	"\x10DeviceCodeStatus\x12\"\n" +
	"\x1eDEVICE_CODE_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDEVICE_CODE_STATUS_UNKNOWN\x10\x01\x12,\n" +
	"(DEVICE_CODE_STATUS_AUTHORIZATION_PENDING\x10\x02\x12+\n" +
	"'DEVICE_CODE_STATUS_CONFIRMATION_PENDING\x10\x03\x12 \n" +
	"\x1cDEVICE_CODE_STATUS_VALIDATED\x10\x04\x12\x1d\n" +
	"\x19DEVICE_CODE_STATUS_DENIED\x10\x05B-Z+zntr.io/solid/api/oidc/session/v1;sessionv1b\x06proto3"

var (
	file_oidc_session_v1_session_proto_rawDescOnce sync.Once
	file_oidc_session_v1_session_proto_rawDescData []byte
)

func file_oidc_session_v1_session_proto_rawDescGZIP() []byte {
	file_oidc_session_v1_session_proto_rawDescOnce.Do(func() {
		file_oidc_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oidc_session_v1_session_proto_rawDesc), len(file_oidc_session_v1_session_proto_rawDesc)))
	})
	return file_oidc_session_v1_session_proto_rawDescData
}

var file_oidc_session_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_oidc_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oidc_session_v1_session_proto_goTypes = []any{
	(AuthorizationCodeStatus)(0),           // 0: oidc.session.v1.AuthorizationCodeStatus
	(DeviceCodeStatus)(0),                  // 1: oidc.session.v1.DeviceCodeStatus
	(*AuthorizationCodeSession)(nil),       // 2: oidc.session.v1.AuthorizationCodeSession
	(*DeviceCodeSession)(nil),              // 3: oidc.session.v1.DeviceCodeSession
	(*v1.Client)(nil),                      // 4: oidc.client.v1.Client
	(*v11.AuthorizationRequest)(nil),       // 5: oidc.flow.v1.AuthorizationRequest
	(*v12.TokenConfirmation)(nil),          // 6: oidc.token.v1.TokenConfirmation
	(*v11.DeviceAuthorizationRequest)(nil), // 7: oidc.flow.v1.DeviceAuthorizationRequest
	(*v12.AuthorizationDetail)(nil),        // 8: oidc.token.v1.AuthorizationDetail
}
var file_oidc_session_v1_session_proto_depIdxs = []int32{
	4, // 0: oidc.session.v1.AuthorizationCodeSession.client:type_name -> oidc.client.v1.Client
	5, // 1: oidc.session.v1.AuthorizationCodeSession.request:type_name -> oidc.flow.v1.AuthorizationRequest
	0, // 2: oidc.session.v1.AuthorizationCodeSession.status:type_name -> oidc.session.v1.AuthorizationCodeStatus
	6, // 3: oidc.session.v1.AuthorizationCodeSession.confirmation:type_name -> oidc.token.v1.TokenConfirmation
	4, // 4: oidc.session.v1.DeviceCodeSession.client:type_name -> oidc.client.v1.Client
	7, // 5: oidc.session.v1.DeviceCodeSession.request:type_name -> oidc.flow.v1.DeviceAuthorizationRequest
	1, // 6: oidc.session.v1.DeviceCodeSession.status:type_name -> oidc.session.v1.DeviceCodeStatus
	8, // 7: oidc.session.v1.DeviceCodeSession.authorization_details:type_name -> oidc.token.v1.AuthorizationDetail
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_oidc_session_v1_session_proto_init() }
func file_oidc_session_v1_session_proto_init() {
	if File_oidc_session_v1_session_proto != nil {
		return
	}
	file_oidc_session_v1_session_proto_msgTypes[0].OneofWrappers = []any{}
	file_oidc_session_v1_session_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oidc_session_v1_session_proto_rawDesc), len(file_oidc_session_v1_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oidc_session_v1_session_proto_goTypes,
		DependencyIndexes: file_oidc_session_v1_session_proto_depIdxs,
		EnumInfos:         file_oidc_session_v1_session_proto_enumTypes,
		MessageInfos:      file_oidc_session_v1_session_proto_msgTypes,
	}.Build()
	File_oidc_session_v1_session_proto = out.File
	file_oidc_session_v1_session_proto_goTypes = nil
	file_oidc_session_v1_session_proto_depIdxs = nil
}
