// Code generated by MockGen. DO NOT EDIT.
// Source: zntr.io/solid/sdk/idjag (interfaces: IssuerResolver)
//
// Generated by this command:
//
//	mockgen -destination mock/issuerresolver.gen.go -package mock zntr.io/solid/sdk/idjag IssuerResolver
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	jwk "zntr.io/solid/sdk/jwk"
)

// MockIssuerResolver is a mock of IssuerResolver interface.
type MockIssuerResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIssuerResolverMockRecorder
	isgomock struct{}
}

// MockIssuerResolverMockRecorder is the mock recorder for MockIssuerResolver.
type MockIssuerResolverMockRecorder struct {
	mock *MockIssuerResolver
}

// NewMockIssuerResolver creates a new mock instance.
func NewMockIssuerResolver(ctrl *gomock.Controller) *MockIssuerResolver {
	mock := &MockIssuerResolver{ctrl: ctrl}
	mock.recorder = &MockIssuerResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuerResolver) EXPECT() *MockIssuerResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIssuerResolver) Resolve(ctx context.Context, issuer string) (jwk.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, issuer)
	ret0, _ := ret[0].(jwk.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIssuerResolverMockRecorder) Resolve(ctx, issuer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIssuerResolver)(nil).Resolve), ctx, issuer)
}
